// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lightSwitch(lv_event_t * e);
void curtainSwitch(lv_event_t * e);
void loudSpeakerSwitch(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
