// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void lightSwitch(lv_event_t * e)
{
	// Your code here
}

void curtainSwitch(lv_event_t * e)
{
	// Your code here
}

void loudSpeakerSwitch(lv_event_t * e)
{
	// Your code here
}
