// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui_events.h"
#include "ui.h"

// 音乐结构体
struct music
{
	char path[100]; // 歌曲路径名
	char lrc[100];	// 歌词文件
	char pic[100];	// 歌曲封面
};

// 音乐列表
struct music musicList[100] = {
	{"/music/City_Of_Stars.mp3", "NULL", "NULL"},
	{"/music/My_Heart_Will_Go_On.mp3", "NULL", "NULL"},
	{"/music/The_Way_I_Still_Love_You.mp3", "NULL", "NULL"}};

int num = 3; // 音乐列表的长度

int _index = 0;			   // 当前播放歌曲的索引
int is_playing = 0;		   // 0表示暂停，1表示播放
int music_initialized = 0; // 0表示未初始化，1表示已初始化mplayer进程

void *playMusic(void *arg)
{
	// 1.加载mplayer  播放进程
	char cmd[1024] = {0};

	// 当前歌曲信息
	printf("当前播放歌曲：%s\n", musicList[_index].path);
	printf("当前播放歌词：%s\n", musicList[_index].lrc);
	printf("当前播放封面：%s\n", musicList[_index].pic);

	// 2.拼接播放命令
	sprintf(cmd, "mplayer -slave -quiet -input file=/home/gec/pipe %s", musicList[_index].path);

	// 3.执行命令
	FILE *fp = popen(cmd, "r");
	if (fp == NULL)
	{
		perror("popen");
		return NULL;
	}

	// 读取mplayer的输出信息
	while (1)
	{
		char buf[1024] = {0};
		if (fgets(buf, sizeof(buf), fp) == NULL)
		{
			break;
		}
		printf("%s", buf);
	}

	pclose(fp);
}

// 点击切换空调状态
void airOnOffText(lv_event_t *e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	static int airOn = 1; // 0表示关闭，1表示开启

	if (event_code == LV_EVENT_CLICKED)
	{
		if (airOn == 0)
		{
			airOn = 1; // 切换到开启状态
			lv_label_set_text(ui_temperatureText, "26°C");
			lv_label_set_text(ui_airTemperature, "26°C");
		}
		else
		{
			airOn = 0; // 切换到关闭状态
			lv_label_set_text(ui_temperatureText, "Start");
			lv_label_set_text(ui_airTemperature, "Start");
		}
	}
}

void controlChange1(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &light_on);
		lv_image_set_src(ui_lightOffImg, &light_click);
		lv_label_set_text(ui_lightSliderValue, "0%");
		lv_slider_set_value(ui_lightSlider, 0, LV_ANIM_OFF);
	}
}

void controlChange2(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &ui_img_920086830);
		lv_image_set_src(ui_lightOffImg, &ui_img_light_png);
		lv_label_set_text(ui_lightSliderValue, "10%");
		lv_slider_set_value(ui_lightSlider, 10, LV_ANIM_OFF);
	}
}

void controlChange3(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &ui_img_920086830);
		lv_image_set_src(ui_lightOffImg, &ui_img_light_png);
		lv_label_set_text(ui_lightSliderValue, "70%");
		lv_slider_set_value(ui_lightSlider, 70, LV_ANIM_OFF);
	}
}

void controlChange4(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &ui_img_920086830);
		lv_image_set_src(ui_lightOffImg, &ui_img_light_png);
		lv_label_set_text(ui_lightSliderValue, "10%");
		lv_slider_set_value(ui_lightSlider, 10, LV_ANIM_OFF);
	}
}

void controlChange5(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &ui_img_920086830);
		lv_image_set_src(ui_lightOffImg, &ui_img_light_png);
		lv_label_set_text(ui_lightSliderValue, "30%");
		lv_slider_set_value(ui_lightSlider, 30, LV_ANIM_OFF);
	}
}

void controlChange6(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &ui_img_920086830);
		lv_image_set_src(ui_lightOffImg, &ui_img_light_png);
		lv_label_set_text(ui_lightSliderValue, "80%");
		lv_slider_set_value(ui_lightSlider, 80, LV_ANIM_OFF);
	}
}

// 音乐图片数组
const lv_image_dsc_t *music_images[] = {
	&City_Of_Stars,
	&My_Heart_Will_Go_On,
	&The_Way_I_Still_Love_You};

// 音乐名和歌手
char *music_names[] = {
	"City Of Stars",
	"My Heart Will Go On",
	"The Way I Still Love You"};

char *music_singers[] = {
	"周深/米卡",
	"满舒克/MuSik I/廖伟珊",
	"Reynard Silva"};

void startPlay()
{
	// 只有在音乐未初始化时才创建新的播放线程
	if (!music_initialized)
	{
		pthread_t tid;
		pthread_create(&tid, NULL, playMusic, NULL);
		pthread_detach(tid);   // 分离属性
		music_initialized = 1; // 标记为已初始化
	}
}

void playSong(lv_event_t *e, lv_obj_t *ui_play, lv_obj_t *ui_musicInfo, lv_obj_t *ui_songName, lv_obj_t *ui_singer)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		if (is_playing == 0)
		{
			is_playing = 1;								  // 切换到播放状态
			lv_image_set_src(ui_play, &ui_img_pause_png); // 播放时显示暂停图标

			if (!music_initialized)
			{
				lv_obj_set_style_bg_image_src(ui_musicInfo, music_images[_index], LV_PART_MAIN | LV_STATE_DEFAULT);
				lv_label_set_text(ui_songName, music_names[_index]);
				lv_label_set_text(ui_singer, music_singers[_index]);

				// 第一次播放，启动mplayer
				startPlay();
				printf("开始播放音乐\n");
			}
			else
			{
				// 恢复播放，发送pause命令切换状态
				system("echo 'pause' > /home/gec/pipe");
				printf("恢复播放音乐\n");
			}
		}
		else
		{
			is_playing = 0;					  // 切换到暂停状态
			lv_image_set_src(ui_play, &play); // 暂停时显示播放图标
			// 通过管道发送暂停命令给mplayer
			system("echo 'pause' > /home/gec/pipe");
			printf("暂停播放音乐\n");
		}
	}
}

void prevSong(lv_event_t *e, lv_obj_t *ui_last, lv_obj_t *ui_musicInfo, lv_obj_t *ui_songName, lv_obj_t *ui_singer)
{
	printf("上一首\n");
	system("killall mplayer"); // 结束当前播放
	music_initialized = 0;	   // 重置初始化状态
	_index--;
	if (_index < 0)
	{
		_index = 2;
	}
	lv_obj_set_style_bg_image_src(ui_musicInfo, music_images[_index], LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_label_set_text(ui_songName, music_names[_index]);
	lv_label_set_text(ui_singer, music_singers[_index]);

	// 切换歌曲后自动开始播放
	is_playing = 1;								  // 设置播放状态
	lv_image_set_src(ui_play, &ui_img_pause_png); // 播放时显示暂停图标
	startPlay();
}

void nextSong(lv_event_t *e, lv_obj_t *ui_next, lv_obj_t *ui_musicInfo, lv_obj_t *ui_songName, lv_obj_t *ui_singer)
{
	printf("下一首\n");
	system("killall mplayer"); // 结束当前播放
	music_initialized = 0;	   // 重置初始化状态
	_index++;
	if (_index >= num)
	{
		_index = 0;
	}
	// 切换歌曲后自动开始播放
	is_playing = 1; // 设置播放状态
	lv_obj_set_style_bg_image_src(ui_musicInfo, music_images[_index], LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_label_set_text(ui_songName, music_names[_index]);
	lv_label_set_text(ui_singer, music_singers[_index]);

	lv_image_set_src(ui_play, &ui_img_pause_png); // 播放时显示暂停图标
	startPlay();
}

// 减少温度事件
void decreaseTemp(lv_event_t *e, lv_obj_t *ui_airTemperature, lv_obj_t *ui_temperatureText)
{
	// 获取温度标签文本
	char *buf = lv_label_get_text(ui_airTemperature);
	char *degree_sign = strstr(buf, "°C");
	// 转换为整数
	int temp = atoi(buf);
	if (temp > 16) // 假设温度范围为16°C到30°C
		temp -= 1;
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		// 设置新的温度文本
		char new_temp[10];
		sprintf(new_temp, "%d", temp);
		lv_label_set_text(ui_airTemperature, new_temp);
		if (degree_sign)
		{
			lv_label_set_text(ui_airTemperature, strcat(new_temp, "°C"));
			lv_label_set_text(ui_temperatureText, new_temp);
			// ui_temperatureText
		}
	}
}

void increaseTemp(lv_event_t *e, lv_obj_t *ui_airTemperature, lv_obj_t *ui_temperatureText)
{
	// 获取温度标签文本
	char *buf = lv_label_get_text(ui_airTemperature);
	char *degree_sign = strstr(buf, "°C");
	// 转换为整数
	int temp = atoi(buf);
	if (temp < 30)
		temp += 1;
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		// 设置新的温度文本
		char new_temp[10];
		sprintf(new_temp, "%d", temp);
		lv_label_set_text(ui_airTemperature, new_temp);
		if (degree_sign)
		{
			lv_label_set_text(ui_airTemperature, strcat(new_temp, "°C"));
			lv_label_set_text(ui_temperatureText, new_temp);
		}
	}
}

// 灯全开全关事件
void lightAllOn(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &ui_img_920086830);
		lv_image_set_src(ui_lightOffImg, &ui_img_light_png);
		lv_label_set_text(ui_lightSliderValue, "50%");
		lv_slider_set_value(ui_lightSlider, 50, LV_ANIM_OFF);
	}
}

void lightAllOff(lv_event_t *e, lv_obj_t *ui_lightOnImg, lv_obj_t *ui_lightOffImg, lv_obj_t *ui_lightSliderValue, lv_obj_t *ui_lightSlider)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_lightOnImg, &light_on);
		lv_image_set_src(ui_lightOffImg, &light_click);
		lv_label_set_text(ui_lightSliderValue, "0%");
		lv_slider_set_value(ui_lightSlider, 0, LV_ANIM_OFF);
	}
}

void curtainAllOn(lv_event_t *e, lv_obj_t *ui_curtainOnImg, lv_obj_t *ui_curtainOffImg)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_curtainOnImg, &ui_img_1611275694);
		lv_image_set_src(ui_curtainOffImg, &ui_img_1850939063);
	}
}

void curtainAllOff(lv_event_t *e, lv_obj_t *ui_curtainOnImg, lv_obj_t *ui_curtainOffImg)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED)
	{
		lv_image_set_src(ui_curtainOnImg, &curtain);
		lv_image_set_src(ui_curtainOffImg, &window_shade_click);
	}
}

// 跳转屏幕函数
void roomChange(lv_event_t *e)
{
	lv_obj_t *dropdown = lv_event_get_target(e);
	uint32_t selected = lv_dropdown_get_selected(dropdown);

	switch (selected)
	{
	case 0: // 客厅 - 跳转到Screen1
		lv_screen_load(ui_Screen1);
		break;
	case 1: // 主卧 - 跳转到Screen2
		lv_screen_load(ui_Screen2);
		break;
	case 2: // 次卧 - 跳转到Screen3
		lv_screen_load(ui_Screen3);
		break;
	default:
		break;
	}
}
