// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void controlChange1(lv_event_t * e);
void controlChange2(lv_event_t * e);
void controlChange3(lv_event_t * e);
void controlChange4(lv_event_t * e);
void controlChange5(lv_event_t * e);
void controlChange6(lv_event_t * e);
void playSong(lv_event_t * e);
void prevSong(lv_event_t * e);
void nextSong(lv_event_t * e);
void decreaseTemp(lv_event_t * e);
void increaseTemp(lv_event_t * e);
void lightAllOn(lv_event_t * e);
void lightAllOff(lv_event_t * e);
void curtainAllOn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
