// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void controlChange1(lv_event_t * e)
{
	// Your code here
}

void controlChange2(lv_event_t * e)
{
	// Your code here
}

void controlChange3(lv_event_t * e)
{
	// Your code here
}

void controlChange4(lv_event_t * e)
{
	// Your code here
}

void controlChange5(lv_event_t * e)
{
	// Your code here
}

void controlChange6(lv_event_t * e)
{
	// Your code here
}

void playSong(lv_event_t * e)
{
	// Your code here
}

void prevSong(lv_event_t * e)
{
	// Your code here
}

void nextSong(lv_event_t * e)
{
	// Your code here
}

void decreaseTemp(lv_event_t * e)
{
	// Your code here
}

void increaseTemp(lv_event_t * e)
{
	// Your code here
}

void lightAllOn(lv_event_t * e)
{
	// Your code here
}

void lightAllOff(lv_event_t * e)
{
	// Your code here
}

void curtainAllOn(lv_event_t * e)
{
	// Your code here
}
