// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_entirety1;
extern lv_obj_t * ui_header1;
extern lv_obj_t * ui_Logo1;
extern lv_obj_t * ui_LogoImg1;
extern lv_obj_t * ui_roomCut1;
extern lv_obj_t * ui_roomImg1;
extern lv_obj_t * ui_ChangeRoom1;
extern lv_obj_t * ui_currentTime1;
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_Date1;
extern lv_obj_t * ui_weather1;
extern lv_obj_t * ui_weatherIcon1;
extern lv_obj_t * ui_temperature2;
extern lv_obj_t * ui_states1;
extern lv_obj_t * ui_wifi1;
extern lv_obj_t * ui_battery1;
extern lv_obj_t * ui_temperature3;
extern lv_obj_t * ui_main1;
extern lv_obj_t * ui_controlState1;
extern void ui_event_goHome1(lv_event_t * e);
extern lv_obj_t * ui_goHome1;
extern lv_obj_t * ui_home1;
extern lv_obj_t * ui_goHomeText1;
extern void ui_event_gobed1(lv_event_t * e);
extern lv_obj_t * ui_gobed1;
extern lv_obj_t * ui_bed1;
extern lv_obj_t * ui_goBedText1;
extern void ui_event_relex1(lv_event_t * e);
extern lv_obj_t * ui_relex1;
extern lv_obj_t * ui_yoga1;
extern lv_obj_t * ui_relexText1;
extern void ui_event_getUp1(lv_event_t * e);
extern lv_obj_t * ui_getUp1;
extern lv_obj_t * ui_tea1;
extern lv_obj_t * ui_getUpText1;
extern void ui_event_cinema1(lv_event_t * e);
extern lv_obj_t * ui_cinema1;
extern lv_obj_t * ui_tape1;
extern lv_obj_t * ui_cinemaText1;
extern void ui_event_goOut1(lv_event_t * e);
extern lv_obj_t * ui_goOut1;
extern lv_obj_t * ui_goOutImg1;
extern lv_obj_t * ui_goOutText1;
extern lv_obj_t * ui_controlPanel1;
extern lv_obj_t * ui_lightInfo1;
extern lv_obj_t * ui_lightInfoTitle1;
extern lv_obj_t * ui_lightSliderValue1;
extern void ui_event_lightSlider1(lv_event_t * e);
extern lv_obj_t * ui_lightSlider1;
extern lv_obj_t * ui_airInfo1;
extern lv_obj_t * ui_airInfoTitle1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_airTemperature1;
extern lv_obj_t * ui_airTemperatureText1;
extern lv_obj_t * ui_weatherInfo1;
extern lv_obj_t * ui_weatherInfoText1;
extern lv_obj_t * ui_weatherTemperature1;
extern lv_obj_t * ui_weatherState1;
extern lv_obj_t * ui_weatherImg1;
extern lv_obj_t * ui_musicInfo1;
extern lv_obj_t * ui_musicInfoText1;
extern lv_obj_t * ui_singer1;
extern lv_obj_t * ui_songName1;
extern lv_obj_t * ui_playControl1;
extern void ui_event_play1(lv_event_t * e);
extern lv_obj_t * ui_play1;
extern void ui_event_last1(lv_event_t * e);
extern lv_obj_t * ui_last1;
extern void ui_event_next1(lv_event_t * e);
extern lv_obj_t * ui_next1;
extern lv_obj_t * ui_footer1;
extern lv_obj_t * ui_airControl1;
extern void ui_event_lower1(lv_event_t * e);
extern lv_obj_t * ui_lower1;
extern void ui_event_increase1(lv_event_t * e);
extern lv_obj_t * ui_increase1;
extern void ui_event_temperatureText1(lv_event_t * e);
extern lv_obj_t * ui_temperatureText1;
extern lv_obj_t * ui_footerLeft1;
extern lv_obj_t * ui_lightOn1;
extern void ui_event_lightOnImg1(lv_event_t * e);
extern lv_obj_t * ui_lightOnImg1;
extern lv_obj_t * ui_lightOnText1;
extern lv_obj_t * ui_lightOff2;
extern void ui_event_lightOffImg1(lv_event_t * e);
extern lv_obj_t * ui_lightOffImg1;
extern lv_obj_t * ui_lightOffText1;
extern lv_obj_t * ui_footerRight1;
extern lv_obj_t * ui_curtainOn1;
extern void ui_event_curtainOnImg1(lv_event_t * e);
extern lv_obj_t * ui_curtainOnImg1;
extern lv_obj_t * ui_curtainOnText1;
extern lv_obj_t * ui_lightOff3;
extern void ui_event_curtainOffImg1(lv_event_t * e);
extern lv_obj_t * ui_curtainOffImg1;
extern lv_obj_t * ui_curtainOffText1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

