// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_time_manager.h"
#include "ui_weather.h"

lv_obj_t *ui_Screen3 = NULL;
lv_obj_t *ui_entirety2 = NULL;
lv_obj_t *ui_header2 = NULL;
lv_obj_t *ui_Logo2 = NULL;
lv_obj_t *ui_LogoImg2 = NULL;
lv_obj_t *ui_roomCut2 = NULL;
lv_obj_t *ui_roomImg2 = NULL;
lv_obj_t *ui_ChangeRoom2 = NULL;
lv_obj_t *ui_currentTime2 = NULL;
lv_obj_t *ui_Time2 = NULL;
lv_obj_t *ui_Date2 = NULL;
lv_obj_t *ui_weather2 = NULL;
lv_obj_t *ui_weatherIcon2 = NULL;
lv_obj_t *ui_temperature4 = NULL;
lv_obj_t *ui_states2 = NULL;
lv_obj_t *ui_wifi2 = NULL;
lv_obj_t *ui_battery2 = NULL;
lv_obj_t *ui_temperature5 = NULL;
lv_obj_t *ui_main2 = NULL;
lv_obj_t *ui_controlState2 = NULL;
lv_obj_t *ui_goHome2 = NULL;
lv_obj_t *ui_home2 = NULL;
lv_obj_t *ui_goHomeText2 = NULL;
lv_obj_t *ui_gobed2 = NULL;
lv_obj_t *ui_bed2 = NULL;
lv_obj_t *ui_goBedText2 = NULL;
lv_obj_t *ui_relex2 = NULL;
lv_obj_t *ui_yoga2 = NULL;
lv_obj_t *ui_relexText2 = NULL;
lv_obj_t *ui_getUp2 = NULL;
lv_obj_t *ui_tea2 = NULL;
lv_obj_t *ui_getUpText2 = NULL;
lv_obj_t *ui_cinema2 = NULL;
lv_obj_t *ui_tape2 = NULL;
lv_obj_t *ui_cinemaText2 = NULL;
lv_obj_t *ui_goOut2 = NULL;
lv_obj_t *ui_goOutImg2 = NULL;
lv_obj_t *ui_goOutText2 = NULL;
lv_obj_t *ui_controlPanel2 = NULL;
lv_obj_t *ui_lightInfo2 = NULL;
lv_obj_t *ui_lightInfoTitle2 = NULL;
lv_obj_t *ui_lightSliderValue2 = NULL;
lv_obj_t *ui_lightSlider2 = NULL;
lv_obj_t *ui_airInfo2 = NULL;
lv_obj_t *ui_airInfoTitle2 = NULL;
lv_obj_t *ui_Panel3 = NULL;
lv_obj_t *ui_airTemperature2 = NULL;
lv_obj_t *ui_airTemperatureText2 = NULL;
lv_obj_t *ui_weatherInfo2 = NULL;
lv_obj_t *ui_weatherInfoText2 = NULL;
lv_obj_t *ui_weatherTemperature2 = NULL;
lv_obj_t *ui_weatherState2 = NULL;
lv_obj_t *ui_weatherImg2 = NULL;
lv_obj_t *ui_musicInfo2 = NULL;
lv_obj_t *ui_musicInfoText2 = NULL;
lv_obj_t *ui_singer2 = NULL;
lv_obj_t *ui_songName2 = NULL;
lv_obj_t *ui_playControl2 = NULL;
lv_obj_t *ui_play2 = NULL;
lv_obj_t *ui_last2 = NULL;
lv_obj_t *ui_next2 = NULL;
lv_obj_t *ui_footer2 = NULL;
lv_obj_t *ui_airControl2 = NULL;
lv_obj_t *ui_lower2 = NULL;
lv_obj_t *ui_increase2 = NULL;
lv_obj_t *ui_temperatureText2 = NULL;
lv_obj_t *ui_footerLeft2 = NULL;
lv_obj_t *ui_lightOn2 = NULL;
lv_obj_t *ui_lightOnImg2 = NULL;
lv_obj_t *ui_lightOnText2 = NULL;
lv_obj_t *ui_lightOff4 = NULL;
lv_obj_t *ui_lightOffImg2 = NULL;
lv_obj_t *ui_lightOffText2 = NULL;
lv_obj_t *ui_footerRight2 = NULL;
lv_obj_t *ui_curtainOn2 = NULL;
lv_obj_t *ui_curtainOnImg2 = NULL;
lv_obj_t *ui_curtainOnText2 = NULL;
lv_obj_t *ui_lightOff5 = NULL;
lv_obj_t *ui_curtainOffImg2 = NULL;
lv_obj_t *ui_curtainOffText2 = NULL;

// event funtions
void ui_event_ChangeRoom2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        roomChange(e);
    }
}

void ui_event_goHome2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange1(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_gobed2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange2(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_relex2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange3(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_getUp2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange4(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_cinema2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange5(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_goOut2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange6(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_lightSlider2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_slider_set_text_value(ui_lightSliderValue2, target, "", "%");
    }
}

void ui_event_play2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        playSong(e, ui_play2, ui_musicInfo2, ui_songName2, ui_singer2);
    }
}

void ui_event_last2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        prevSong(e, ui_last2, ui_musicInfo2, ui_songName2, ui_singer2);
    }
}

void ui_event_next2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        nextSong(e, ui_next2, ui_musicInfo2, ui_songName2, ui_singer2);
    }
}

void ui_event_lower2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        decreaseTemp(e, ui_airTemperature2, ui_temperatureText2);
    }
}

void ui_event_increase2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        increaseTemp(e, ui_airTemperature2, ui_temperatureText2);
    }
}

void ui_event_temperatureText2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_checked_set_text_value(ui_airTemperature2, target, "", "°C");
    }
}

void ui_event_lightOnImg2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        lightAllOn(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_lightOffImg2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        lightAllOff(e, ui_lightOnImg2, ui_lightOffImg2, ui_lightSliderValue2, ui_lightSlider2);
    }
}

void ui_event_curtainOnImg2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        curtainAllOn(e, ui_curtainOnImg2, ui_curtainOffImg2);
    }
}

void ui_event_curtainOffImg2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        curtainAllOff(e, ui_curtainOnImg2, ui_curtainOffImg2);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen3, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_entirety2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_entirety2, 800);
    lv_obj_set_height(ui_entirety2, 480);
    lv_obj_set_align(ui_entirety2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_entirety2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_entirety2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_entirety2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_entirety2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header2 = lv_obj_create(ui_entirety2);
    lv_obj_set_width(ui_header2, 750);
    lv_obj_set_height(ui_header2, 50);
    lv_obj_set_align(ui_header2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_header2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_header2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo2 = lv_obj_create(ui_header2);
    lv_obj_set_width(ui_Logo2, 100);
    lv_obj_set_height(ui_Logo2, 50);
    lv_obj_set_align(ui_Logo2, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Logo2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Logo2, lv_color_hex(0x0C0C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Logo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Logo2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImg2 = lv_image_create(ui_Logo2);
    lv_image_set_src(ui_LogoImg2, &ui_img_home_png);
    lv_obj_set_width(ui_LogoImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LogoImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LogoImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LogoImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_roomCut2 = lv_obj_create(ui_header2);
    lv_obj_set_width(ui_roomCut2, 150);
    lv_obj_set_height(ui_roomCut2, 50);
    lv_obj_set_x(ui_roomCut2, 120);
    lv_obj_set_y(ui_roomCut2, 0);
    lv_obj_set_align(ui_roomCut2, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_roomCut2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_roomCut2, lv_color_hex(0x101314), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roomCut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_roomCut2, lv_color_hex(0x959595), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_roomCut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_roomCut2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomImg2 = lv_image_create(ui_roomCut2);
    lv_image_set_src(ui_roomImg2, &ui_img_sofa_png);
    lv_obj_set_width(ui_roomImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_roomImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_roomImg2, -10);
    lv_obj_set_y(ui_roomImg2, 0);
    lv_obj_set_align(ui_roomImg2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_roomImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_roomImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ChangeRoom2 = lv_dropdown_create(ui_roomCut2);
    lv_dropdown_set_options(ui_ChangeRoom2, "客厅\n主卧\n次卧");
    lv_dropdown_set_selected_highlight(ui_ChangeRoom2, false);
    lv_dropdown_set_text(ui_ChangeRoom2, "次卧");
    lv_obj_set_width(ui_ChangeRoom2, 100);
    lv_obj_set_height(ui_ChangeRoom2, 50);
    lv_obj_set_x(ui_ChangeRoom2, 25);
    lv_obj_set_y(ui_ChangeRoom2, 0);
    lv_obj_set_align(ui_ChangeRoom2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChangeRoom2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_text_color(ui_ChangeRoom2, lv_color_hex(0x8E8E8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChangeRoom2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChangeRoom2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChangeRoom2, lv_color_hex(0x141316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeRoom2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeRoom2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_ChangeRoom2, &lv_font_montserrat_16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ChangeRoom2), lv_color_hex(0x7D7D7B),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ChangeRoom2), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ChangeRoom2), &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ChangeRoom2), lv_color_hex(0x131416),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ChangeRoom2), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_dropdown_get_list(ui_ChangeRoom2), LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ChangeRoom2), lv_color_hex(0x666666),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ChangeRoom2), 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_currentTime2 = lv_obj_create(ui_header2);
    lv_obj_set_width(ui_currentTime2, 150);
    lv_obj_set_height(ui_currentTime2, 50);
    lv_obj_set_align(ui_currentTime2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_currentTime2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_currentTime2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_currentTime2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_currentTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_currentTime2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_currentTime2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time2 = lv_label_create(ui_currentTime2);
    lv_obj_set_width(ui_Time2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Time2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Time2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Time2, "14:20");
    lv_obj_set_style_text_color(ui_Time2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date2 = lv_label_create(ui_currentTime2);
    lv_obj_set_width(ui_Date2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Date2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date2, "2025年8月9日");
    lv_obj_set_style_text_color(ui_Date2, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date2, &ui_font_Date, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather2 = lv_obj_create(ui_header2);
    lv_obj_set_width(ui_weather2, 110);
    lv_obj_set_height(ui_weather2, 50);
    lv_obj_set_x(ui_weather2, -160);
    lv_obj_set_y(ui_weather2, 0);
    lv_obj_set_align(ui_weather2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_weather2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_weather2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_weather2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherIcon2 = lv_image_create(ui_weather2);
    if (strcmp(weather_str, "晴") == 0)
        lv_image_set_src(ui_weatherIcon2, &ui_img_sun_png);
    else if (strcmp(weather_str, "小雨") == 0)
        lv_image_set_src(ui_weatherIcon2, &light_rain);
    else if (strcmp(weather_str, "中雨") == 0)
        lv_image_set_src(ui_weatherIcon2, &mid_rain);
    else if (strcmp(weather_str, "大雨") == 0)
        lv_image_set_src(ui_weatherIcon2, &heavy_rain);
    else if (strcmp(weather_str, "多云") == 0)
        lv_image_set_src(ui_weatherIcon2, &cloudy);
    else if (strcmp(weather_str, "阴") == 0)
        lv_image_set_src(ui_weatherIcon2, &cloud);
    else if (strcmp(weather_str, "雾") == 0)
        lv_image_set_src(ui_weatherIcon2, &fog);
    lv_obj_set_width(ui_weatherIcon2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherIcon2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherIcon2, 2);
    lv_obj_set_y(ui_weatherIcon2, 0);
    lv_obj_set_align(ui_weatherIcon2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weatherIcon2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weatherIcon2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperature4 = lv_label_create(ui_weather2);
    lv_obj_set_width(ui_temperature4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperature4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperature4, LV_ALIGN_RIGHT_MID);
    char temp_display[32];
    snprintf(temp_display, sizeof(temp_display), "%s°C", temp_str);
    lv_label_set_text(ui_temperature4, temp_display);
    lv_obj_set_style_text_color(ui_temperature4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_states2 = lv_obj_create(ui_header2);
    lv_obj_set_width(ui_states2, 140);
    lv_obj_set_height(ui_states2, 50);
    lv_obj_set_align(ui_states2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_states2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_states2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_states2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_states2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi2 = lv_image_create(ui_states2);
    lv_image_set_src(ui_wifi2, &ui_img_wifi_png);
    lv_obj_set_width(ui_wifi2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifi2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifi2, 2);
    lv_obj_set_y(ui_wifi2, 0);
    lv_obj_set_align(ui_wifi2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_wifi2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_battery2 = lv_image_create(ui_states2);
    lv_image_set_src(ui_battery2, &ui_img_battery_png);
    lv_obj_set_width(ui_battery2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_battery2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_battery2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_battery2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperature5 = lv_label_create(ui_states2);
    lv_obj_set_width(ui_temperature5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperature5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperature5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_temperature5, "80%");
    lv_obj_set_style_text_color(ui_temperature5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main2 = lv_obj_create(ui_entirety2);
    lv_obj_set_width(ui_main2, 750);
    lv_obj_set_height(ui_main2, 300);
    lv_obj_set_x(ui_main2, 0);
    lv_obj_set_y(ui_main2, -15);
    lv_obj_set_align(ui_main2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_main2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_main2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_main2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlState2 = lv_obj_create(ui_main2);
    lv_obj_set_width(ui_controlState2, 245);
    lv_obj_set_height(ui_controlState2, 250);
    lv_obj_set_x(ui_controlState2, 1);
    lv_obj_set_y(ui_controlState2, 0);
    lv_obj_set_align(ui_controlState2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_controlState2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_controlState2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_controlState2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_controlState2, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_controlState2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_controlState2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goHome2 = lv_obj_create(ui_controlState2);
    lv_obj_set_width(ui_goHome2, 95);
    lv_obj_set_height(ui_goHome2, 60);
    lv_obj_remove_flag(ui_goHome2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_goHome2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goHome2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_goHome2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home2 = lv_image_create(ui_goHome2);
    lv_image_set_src(ui_home2, &ui_img_enter_png);
    lv_obj_set_width(ui_home2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_home2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_home2, -10);
    lv_obj_set_y(ui_home2, 0);
    lv_obj_set_align(ui_home2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_home2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_home2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goHomeText2 = lv_label_create(ui_goHome2);
    lv_obj_set_width(ui_goHomeText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goHomeText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goHomeText2, 10);
    lv_obj_set_y(ui_goHomeText2, 0);
    lv_obj_set_align(ui_goHomeText2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goHomeText2, "离开");
    lv_obj_set_style_text_color(ui_goHomeText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goHomeText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goHomeText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gobed2 = lv_obj_create(ui_controlState2);
    lv_obj_set_width(ui_gobed2, 95);
    lv_obj_set_height(ui_gobed2, 60);
    lv_obj_remove_flag(ui_gobed2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_gobed2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gobed2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_gobed2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bed2 = lv_image_create(ui_gobed2);
    lv_image_set_src(ui_bed2, &ui_img_bed_png);
    lv_obj_set_width(ui_bed2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_bed2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_bed2, -10);
    lv_obj_set_y(ui_bed2, 0);
    lv_obj_set_align(ui_bed2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_bed2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bed2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goBedText2 = lv_label_create(ui_gobed2);
    lv_obj_set_width(ui_goBedText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goBedText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goBedText2, 10);
    lv_obj_set_y(ui_goBedText2, 0);
    lv_obj_set_align(ui_goBedText2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goBedText2, "睡觉");
    lv_obj_set_style_text_color(ui_goBedText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goBedText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goBedText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_relex2 = lv_obj_create(ui_controlState2);
    lv_obj_set_width(ui_relex2, 95);
    lv_obj_set_height(ui_relex2, 60);
    lv_obj_remove_flag(ui_relex2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_relex2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_relex2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_relex2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yoga2 = lv_image_create(ui_relex2);
    lv_image_set_src(ui_yoga2, &ui_img_yoga_png);
    lv_obj_set_width(ui_yoga2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_yoga2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_yoga2, -10);
    lv_obj_set_y(ui_yoga2, 0);
    lv_obj_set_align(ui_yoga2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_yoga2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_yoga2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_relexText2 = lv_label_create(ui_relex2);
    lv_obj_set_width(ui_relexText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_relexText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_relexText2, 10);
    lv_obj_set_y(ui_relexText2, 0);
    lv_obj_set_align(ui_relexText2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_relexText2, "放松");
    lv_obj_set_style_text_color(ui_relexText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_relexText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_relexText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getUp2 = lv_obj_create(ui_controlState2);
    lv_obj_set_width(ui_getUp2, 95);
    lv_obj_set_height(ui_getUp2, 60);
    lv_obj_remove_flag(ui_getUp2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_getUp2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_getUp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_getUp2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tea2 = lv_image_create(ui_getUp2);
    lv_image_set_src(ui_tea2, &ui_img_855347034);
    lv_obj_set_width(ui_tea2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tea2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tea2, -10);
    lv_obj_set_y(ui_tea2, 0);
    lv_obj_set_align(ui_tea2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_tea2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tea2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_getUpText2 = lv_label_create(ui_getUp2);
    lv_obj_set_width(ui_getUpText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_getUpText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_getUpText2, 10);
    lv_obj_set_y(ui_getUpText2, 0);
    lv_obj_set_align(ui_getUpText2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_getUpText2, "起床");
    lv_obj_set_style_text_color(ui_getUpText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_getUpText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_getUpText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cinema2 = lv_obj_create(ui_controlState2);
    lv_obj_set_width(ui_cinema2, 95);
    lv_obj_set_height(ui_cinema2, 60);
    lv_obj_remove_flag(ui_cinema2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_cinema2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cinema2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cinema2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tape2 = lv_image_create(ui_cinema2);
    lv_image_set_src(ui_tape2, &ui_img_cinema_png);
    lv_obj_set_width(ui_tape2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tape2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tape2, -10);
    lv_obj_set_y(ui_tape2, 0);
    lv_obj_set_align(ui_tape2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_tape2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tape2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_cinemaText2 = lv_label_create(ui_cinema2);
    lv_obj_set_width(ui_cinemaText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_cinemaText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_cinemaText2, 10);
    lv_obj_set_y(ui_cinemaText2, 0);
    lv_obj_set_align(ui_cinemaText2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_cinemaText2, "观影");
    lv_obj_set_style_text_color(ui_cinemaText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cinemaText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cinemaText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goOut2 = lv_obj_create(ui_controlState2);
    lv_obj_set_width(ui_goOut2, 95);
    lv_obj_set_height(ui_goOut2, 60);
    lv_obj_remove_flag(ui_goOut2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_goOut2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goOut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_goOut2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goOutImg2 = lv_image_create(ui_goOut2);
    lv_image_set_src(ui_goOutImg2, &ui_img_logout_png);
    lv_obj_set_width(ui_goOutImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goOutImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goOutImg2, -10);
    lv_obj_set_y(ui_goOutImg2, 0);
    lv_obj_set_align(ui_goOutImg2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_goOutImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_goOutImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goOutText2 = lv_label_create(ui_goOut2);
    lv_obj_set_width(ui_goOutText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goOutText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goOutText2, 10);
    lv_obj_set_y(ui_goOutText2, 0);
    lv_obj_set_align(ui_goOutText2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goOutText2, "进入");
    lv_obj_set_style_text_color(ui_goOutText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goOutText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goOutText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlPanel2 = lv_obj_create(ui_main2);
    lv_obj_set_width(ui_controlPanel2, 480);
    lv_obj_set_height(ui_controlPanel2, 290);
    lv_obj_set_x(ui_controlPanel2, 30);
    lv_obj_set_y(ui_controlPanel2, 0);
    lv_obj_set_align(ui_controlPanel2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_controlPanel2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_controlPanel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_controlPanel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_controlPanel2, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_controlPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_controlPanel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightInfo2 = lv_obj_create(ui_controlPanel2);
    lv_obj_set_width(ui_lightInfo2, 210);
    lv_obj_set_height(ui_lightInfo2, 120);
    lv_obj_set_align(ui_lightInfo2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_lightInfo2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_lightInfo2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightInfo2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightInfo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_lightInfo2, &ui_img_orange_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_lightInfo2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightInfo2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightInfoTitle2 = lv_label_create(ui_lightInfo2);
    lv_obj_set_width(ui_lightInfoTitle2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightInfoTitle2, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_lightInfoTitle2, "照明");
    lv_obj_set_style_text_color(ui_lightInfoTitle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightInfoTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightInfoTitle2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightSliderValue2 = lv_label_create(ui_lightInfo2);
    lv_obj_set_width(ui_lightSliderValue2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightSliderValue2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightSliderValue2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lightSliderValue2, "80%");
    lv_obj_set_style_text_color(ui_lightSliderValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightSliderValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightSlider2 = lv_slider_create(ui_lightInfo2);
    lv_slider_set_value(ui_lightSlider2, 80, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_lightSlider2) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_lightSlider2, 0,
                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_lightSlider2, 150);
    lv_obj_set_height(ui_lightSlider2, 10);
    lv_obj_set_align(ui_lightSlider2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_lightSlider2, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lightSlider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lightSlider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if (lv_obj_get_style_pad_top(ui_lightSlider2, LV_PART_MAIN) > 0)
        lv_obj_set_style_pad_right(ui_lightSlider2,
                                   lv_obj_get_style_pad_right(ui_lightSlider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_airInfo2 = lv_obj_create(ui_controlPanel2);
    lv_obj_set_width(ui_airInfo2, 210);
    lv_obj_set_height(ui_airInfo2, 120);
    lv_obj_set_x(ui_airInfo2, -1);
    lv_obj_set_y(ui_airInfo2, 0);
    lv_obj_set_align(ui_airInfo2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airInfo2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_airInfo2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_airInfo2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airInfo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_airInfo2, &ui_img_blue_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_airInfo2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_airInfo2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airInfoTitle2 = lv_label_create(ui_airInfo2);
    lv_obj_set_width(ui_airInfoTitle2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airInfoTitle2, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_airInfoTitle2, "空调");
    lv_obj_set_style_text_color(ui_airInfoTitle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airInfoTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airInfoTitle2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_airInfo2);
    lv_obj_set_width(ui_Panel3, 150);
    lv_obj_set_height(ui_Panel3, 70);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 5);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airTemperature2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_airTemperature2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airTemperature2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_airTemperature2, 0);
    lv_obj_set_y(ui_airTemperature2, -5);
    lv_obj_set_align(ui_airTemperature2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airTemperature2, "26°C");
    lv_obj_set_style_text_color(ui_airTemperature2, lv_color_hex(0xA1A2A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airTemperature2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airTemperature2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airTemperatureText2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_airTemperatureText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airTemperatureText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_airTemperatureText2, 0);
    lv_obj_set_y(ui_airTemperatureText2, 20);
    lv_obj_set_align(ui_airTemperatureText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airTemperatureText2, "温度");
    lv_obj_set_style_text_color(ui_airTemperatureText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airTemperatureText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airTemperatureText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherInfo2 = lv_obj_create(ui_controlPanel2);
    lv_obj_set_width(ui_weatherInfo2, 210);
    lv_obj_set_height(ui_weatherInfo2, 120);
    lv_obj_set_align(ui_weatherInfo2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherInfo2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_weatherInfo2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weatherInfo2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherInfo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_weatherInfo2, &ui_img_green_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_weatherInfo2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_weatherInfo2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherInfoText2 = lv_label_create(ui_weatherInfo2);
    lv_obj_set_width(ui_weatherInfoText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherInfoText2, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_weatherInfoText2, "天气");
    lv_obj_set_style_text_color(ui_weatherInfoText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherInfoText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherInfoText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherTemperature2 = lv_label_create(ui_weatherInfo2);
    lv_obj_set_width(ui_weatherTemperature2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherTemperature2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_weatherTemperature2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_weatherTemperature2, temp_display);
    lv_obj_set_style_text_color(ui_weatherTemperature2, lv_color_hex(0xA1A2A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherTemperature2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherTemperature2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherState2 = lv_label_create(ui_weatherInfo2);
    lv_obj_set_width(ui_weatherState2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherState2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherState2, 15);
    lv_obj_set_y(ui_weatherState2, 0);
    lv_obj_set_align(ui_weatherState2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherState2, weather_str);
    lv_obj_set_style_text_color(ui_weatherState2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherState2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherState2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherImg2 = lv_image_create(ui_weatherInfo2);
    if (strcmp(weather_str, "晴") == 0)
        lv_image_set_src(ui_weatherImg2, &ui_img_sun_png);
    else if (strcmp(weather_str, "小雨") == 0)
        lv_image_set_src(ui_weatherImg2, &light_rain);
    else if (strcmp(weather_str, "中雨") == 0)
        lv_image_set_src(ui_weatherImg2, &mid_rain);
    else if (strcmp(weather_str, "大雨") == 0)
        lv_image_set_src(ui_weatherImg2, &heavy_rain);
    else if (strcmp(weather_str, "多云") == 0)
        lv_image_set_src(ui_weatherImg2, &cloudy);
    else if (strcmp(weather_str, "阴") == 0)
        lv_image_set_src(ui_weatherImg2, &cloud);
    else if (strcmp(weather_str, "雾") == 0)
        lv_image_set_src(ui_weatherImg2, &fog);
    lv_obj_set_width(ui_weatherImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherImg2, -15);
    lv_obj_set_y(ui_weatherImg2, 0);
    lv_obj_set_align(ui_weatherImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weatherImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_musicInfo2 = lv_obj_create(ui_controlPanel2);
    lv_obj_set_width(ui_musicInfo2, 210);
    lv_obj_set_height(ui_musicInfo2, 120);
    lv_obj_set_x(ui_musicInfo2, -1);
    lv_obj_set_y(ui_musicInfo2, -3);
    lv_obj_set_align(ui_musicInfo2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_musicInfo2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_musicInfo2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_musicInfo2, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicInfo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_musicInfo2, &ui_img_purple_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_musicInfo2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_musicInfo2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musicInfoText2 = lv_label_create(ui_musicInfo2);
    lv_obj_set_width(ui_musicInfoText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_musicInfoText2, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_musicInfoText2, "音乐");
    lv_obj_set_style_text_color(ui_musicInfoText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_musicInfoText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_musicInfoText2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_singer2 = lv_label_create(ui_musicInfo2);
    lv_obj_set_width(ui_singer2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_singer2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_singer2, 0);
    lv_obj_set_y(ui_singer2, -5);
    lv_obj_set_align(ui_singer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_singer2, "Ed Sheeran");
    lv_obj_set_style_text_color(ui_singer2, lv_color_hex(0x989899), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_singer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_singer2, &ui_font_musicMode14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songName2 = lv_label_create(ui_musicInfo2);
    lv_obj_set_width(ui_songName2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_songName2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_songName2, 0);
    lv_obj_set_y(ui_songName2, 10);
    lv_obj_set_align(ui_songName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_songName2, "Perfect");
    lv_obj_set_style_text_color(ui_songName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_songName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_songName2, &ui_font_musicMode16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playControl2 = lv_obj_create(ui_musicInfo2);
    lv_obj_set_width(ui_playControl2, 200);
    lv_obj_set_height(ui_playControl2, 40);
    lv_obj_set_x(ui_playControl2, 0);
    lv_obj_set_y(ui_playControl2, 20);
    lv_obj_set_align(ui_playControl2, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_playControl2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_playControl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playControl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playControl2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_play2 = lv_image_create(ui_playControl2);
    lv_image_set_src(ui_play2, &play);
    lv_obj_set_width(ui_play2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_play2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_play2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_play2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_last2 = lv_image_create(ui_playControl2);
    lv_image_set_src(ui_last2, &ui_img_214448395);
    lv_obj_set_width(ui_last2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_last2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_last2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_last2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_last2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_next2 = lv_image_create(ui_playControl2);
    lv_image_set_src(ui_next2, &ui_img_end_png);
    lv_obj_set_width(ui_next2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_next2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_next2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_next2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_footer2 = lv_obj_create(ui_entirety2);
    lv_obj_set_width(ui_footer2, 710);
    lv_obj_set_height(ui_footer2, 80);
    lv_obj_set_align(ui_footer2, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_footer2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footer2, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footer2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airControl2 = lv_obj_create(ui_footer2);
    lv_obj_set_width(ui_airControl2, 250);
    lv_obj_set_height(ui_airControl2, 40);
    lv_obj_set_align(ui_airControl2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airControl2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_airControl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airControl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_airControl2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lower2 = lv_image_create(ui_airControl2);
    lv_image_set_src(ui_lower2, &ui_img_back_png);
    lv_obj_set_width(ui_lower2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lower2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lower2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_lower2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lower2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_increase2 = lv_image_create(ui_airControl2);
    lv_image_set_src(ui_increase2, &ui_img_forward_png);
    lv_obj_set_width(ui_increase2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_increase2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_increase2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_increase2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_increase2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperatureText2 = lv_label_create(ui_airControl2);
    lv_obj_set_width(ui_temperatureText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperatureText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperatureText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureText2, "26°C");
    lv_obj_set_style_text_color(ui_temperatureText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperatureText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperatureText2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_footerLeft2 = lv_obj_create(ui_footer2);
    lv_obj_set_width(ui_footerLeft2, 200);
    lv_obj_set_height(ui_footerLeft2, 80);
    lv_obj_set_align(ui_footerLeft2, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_footerLeft2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footerLeft2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerLeft2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footerLeft2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOn2 = lv_obj_create(ui_footerLeft2);
    lv_obj_set_width(ui_lightOn2, 69);
    lv_obj_set_height(ui_lightOn2, 80);
    lv_obj_set_x(ui_lightOn2, 0);
    lv_obj_set_y(ui_lightOn2, 5);
    lv_obj_set_align(ui_lightOn2, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_lightOn2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOn2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOnImg2 = lv_image_create(ui_lightOn2);
    lv_image_set_src(ui_lightOnImg2, &ui_img_920086830);
    lv_obj_set_width(ui_lightOnImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOnImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lightOnImg2, 0);
    lv_obj_set_y(ui_lightOnImg2, -10);
    lv_obj_set_align(ui_lightOnImg2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_lightOnImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lightOnImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_lightOnText2 = lv_label_create(ui_lightOn2);
    lv_obj_set_width(ui_lightOnText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOnText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightOnText2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lightOnText2, "灯全开");
    lv_obj_set_style_text_color(ui_lightOnText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightOnText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightOnText2, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOff4 = lv_obj_create(ui_footerLeft2);
    lv_obj_set_width(ui_lightOff4, 69);
    lv_obj_set_height(ui_lightOff4, 80);
    lv_obj_set_x(ui_lightOff4, 0);
    lv_obj_set_y(ui_lightOff4, 5);
    lv_obj_set_align(ui_lightOff4, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_lightOff4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOff4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOff4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOff4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOffImg2 = lv_image_create(ui_lightOff4);
    lv_image_set_src(ui_lightOffImg2, &ui_img_light_png);
    lv_obj_set_width(ui_lightOffImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOffImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lightOffImg2, 0);
    lv_obj_set_y(ui_lightOffImg2, -10);
    lv_obj_set_align(ui_lightOffImg2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_lightOffImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lightOffImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_lightOffText2 = lv_label_create(ui_lightOff4);
    lv_obj_set_width(ui_lightOffText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOffText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightOffText2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lightOffText2, "灯全关");
    lv_obj_set_style_text_color(ui_lightOffText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightOffText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightOffText2, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_footerRight2 = lv_obj_create(ui_footer2);
    lv_obj_set_width(ui_footerRight2, 200);
    lv_obj_set_height(ui_footerRight2, 80);
    lv_obj_set_align(ui_footerRight2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_footerRight2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footerRight2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerRight2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footerRight2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOn2 = lv_obj_create(ui_footerRight2);
    lv_obj_set_width(ui_curtainOn2, 69);
    lv_obj_set_height(ui_curtainOn2, 80);
    lv_obj_set_x(ui_curtainOn2, 0);
    lv_obj_set_y(ui_curtainOn2, 5);
    lv_obj_set_align(ui_curtainOn2, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_curtainOn2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_curtainOn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtainOn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_curtainOn2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOnImg2 = lv_image_create(ui_curtainOn2);
    lv_image_set_src(ui_curtainOnImg2, &ui_img_1611275694);
    lv_obj_set_width(ui_curtainOnImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOnImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_curtainOnImg2, 0);
    lv_obj_set_y(ui_curtainOnImg2, -10);
    lv_obj_set_align(ui_curtainOnImg2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_curtainOnImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtainOnImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_curtainOnText2 = lv_label_create(ui_curtainOn2);
    lv_obj_set_width(ui_curtainOnText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOnText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_curtainOnText2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_curtainOnText2, "窗帘全开");
    lv_obj_set_style_text_color(ui_curtainOnText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_curtainOnText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_curtainOnText2, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOff5 = lv_obj_create(ui_footerRight2);
    lv_obj_set_width(ui_lightOff5, 69);
    lv_obj_set_height(ui_lightOff5, 80);
    lv_obj_set_x(ui_lightOff5, 0);
    lv_obj_set_y(ui_lightOff5, 5);
    lv_obj_set_align(ui_lightOff5, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_lightOff5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOff5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOff5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOff5, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOffImg2 = lv_image_create(ui_lightOff5);
    lv_image_set_src(ui_curtainOffImg2, &ui_img_1850939063);
    lv_obj_set_width(ui_curtainOffImg2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOffImg2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_curtainOffImg2, 0);
    lv_obj_set_y(ui_curtainOffImg2, -10);
    lv_obj_set_align(ui_curtainOffImg2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_curtainOffImg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtainOffImg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_curtainOffText2 = lv_label_create(ui_lightOff5);
    lv_obj_set_width(ui_curtainOffText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOffText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_curtainOffText2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_curtainOffText2, "窗帘全关");
    lv_obj_set_style_text_color(ui_curtainOffText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_curtainOffText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_curtainOffText2, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_goHome2, ui_event_goHome2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gobed2, ui_event_gobed2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_relex2, ui_event_relex2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_getUp2, ui_event_getUp2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cinema2, ui_event_cinema2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goOut2, ui_event_goOut2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ChangeRoom2, ui_event_ChangeRoom2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightSlider2, ui_event_lightSlider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_play2, ui_event_play2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_last2, ui_event_last2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_next2, ui_event_next2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lower2, ui_event_lower2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_increase2, ui_event_increase2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_temperatureText2, ui_event_temperatureText2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightOnImg2, ui_event_lightOnImg2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightOffImg2, ui_event_lightOffImg2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_curtainOnImg2, ui_event_curtainOnImg2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_curtainOffImg2, ui_event_curtainOffImg2, LV_EVENT_ALL, NULL);

    // 注册时间和日期标签到时间管理器
    ui_time_manager_register_labels(ui_Time2, ui_Date2);

    // 创建一个管道文件
    mkfifo("/home/gec/pipe", 0777);
}

void ui_Screen3_screen_destroy(void)
{
    // 从时间管理器中注销时间标签
    ui_time_manager_unregister_labels(ui_Time2, ui_Date2);

    if (ui_Screen3)
        lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_entirety2 = NULL;
    ui_header2 = NULL;
    ui_Logo2 = NULL;
    ui_LogoImg2 = NULL;
    ui_roomCut2 = NULL;
    ui_roomImg2 = NULL;
    ui_ChangeRoom2 = NULL;
    ui_currentTime2 = NULL;
    ui_Time2 = NULL;
    ui_Date2 = NULL;
    ui_weather2 = NULL;
    ui_weatherIcon2 = NULL;
    ui_temperature4 = NULL;
    ui_states2 = NULL;
    ui_wifi2 = NULL;
    ui_battery2 = NULL;
    ui_temperature5 = NULL;
    ui_main2 = NULL;
    ui_controlState2 = NULL;
    ui_goHome2 = NULL;
    ui_home2 = NULL;
    ui_goHomeText2 = NULL;
    ui_gobed2 = NULL;
    ui_bed2 = NULL;
    ui_goBedText2 = NULL;
    ui_relex2 = NULL;
    ui_yoga2 = NULL;
    ui_relexText2 = NULL;
    ui_getUp2 = NULL;
    ui_tea2 = NULL;
    ui_getUpText2 = NULL;
    ui_cinema2 = NULL;
    ui_tape2 = NULL;
    ui_cinemaText2 = NULL;
    ui_goOut2 = NULL;
    ui_goOutImg2 = NULL;
    ui_goOutText2 = NULL;
    ui_controlPanel2 = NULL;
    ui_lightInfo2 = NULL;
    ui_lightInfoTitle2 = NULL;
    ui_lightSliderValue2 = NULL;
    ui_lightSlider2 = NULL;
    ui_airInfo2 = NULL;
    ui_airInfoTitle2 = NULL;
    ui_Panel3 = NULL;
    ui_airTemperature2 = NULL;
    ui_airTemperatureText2 = NULL;
    ui_weatherInfo2 = NULL;
    ui_weatherInfoText2 = NULL;
    ui_weatherTemperature2 = NULL;
    ui_weatherState2 = NULL;
    ui_weatherImg2 = NULL;
    ui_musicInfo2 = NULL;
    ui_musicInfoText2 = NULL;
    ui_singer2 = NULL;
    ui_songName2 = NULL;
    ui_playControl2 = NULL;
    ui_play2 = NULL;
    ui_last2 = NULL;
    ui_next2 = NULL;
    ui_footer2 = NULL;
    ui_airControl2 = NULL;
    ui_lower2 = NULL;
    ui_increase2 = NULL;
    ui_temperatureText2 = NULL;
    ui_footerLeft2 = NULL;
    ui_lightOn2 = NULL;
    ui_lightOnImg2 = NULL;
    ui_lightOnText2 = NULL;
    ui_lightOff4 = NULL;
    ui_lightOffImg2 = NULL;
    ui_lightOffText2 = NULL;
    ui_footerRight2 = NULL;
    ui_curtainOn2 = NULL;
    ui_curtainOnImg2 = NULL;
    ui_curtainOnText2 = NULL;
    ui_lightOff5 = NULL;
    ui_curtainOffImg2 = NULL;
    ui_curtainOffText2 = NULL;
}
