// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_time_manager.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_entirety = NULL;
lv_obj_t *ui_header = NULL;
lv_obj_t *ui_Logo = NULL;
lv_obj_t *ui_LogoImg = NULL;
lv_obj_t *ui_roomCut = NULL;
lv_obj_t *ui_roomImg = NULL;
lv_obj_t *ui_ChangeRoom = NULL;
lv_obj_t *ui_currentTime = NULL;
lv_obj_t *ui_Time = NULL;
lv_obj_t *ui_Date = NULL;
lv_obj_t *ui_weather = NULL;
lv_obj_t *ui_weatherIcon = NULL;
lv_obj_t *ui_temperature = NULL;
lv_obj_t *ui_states = NULL;
lv_obj_t *ui_wifi = NULL;
lv_obj_t *ui_battery = NULL;
lv_obj_t *ui_temperature1 = NULL;
lv_obj_t *ui_main = NULL;
lv_obj_t *ui_controlState = NULL;
lv_obj_t *ui_goHome = NULL;
lv_obj_t *ui_home = NULL;
lv_obj_t *ui_goHomeText = NULL;
lv_obj_t *ui_gobed = NULL;
lv_obj_t *ui_bed = NULL;
lv_obj_t *ui_goBedText = NULL;
lv_obj_t *ui_relex = NULL;
lv_obj_t *ui_yoga = NULL;
lv_obj_t *ui_relexText = NULL;
lv_obj_t *ui_getUp = NULL;
lv_obj_t *ui_tea = NULL;
lv_obj_t *ui_getUpText = NULL;
lv_obj_t *ui_cinema = NULL;
lv_obj_t *ui_tape = NULL;
lv_obj_t *ui_cinemaText = NULL;
lv_obj_t *ui_goOut = NULL;
lv_obj_t *ui_goOutImg = NULL;
lv_obj_t *ui_goOutText = NULL;
lv_obj_t *ui_controlPanel = NULL;
lv_obj_t *ui_lightInfo = NULL;
lv_obj_t *ui_lightInfoTitle = NULL;
lv_obj_t *ui_lightSliderValue = NULL;
lv_obj_t *ui_lightSlider = NULL;
lv_obj_t *ui_airInfo = NULL;
lv_obj_t *ui_airInfoTitle = NULL;
lv_obj_t *ui_Panel2 = NULL;
lv_obj_t *ui_airTemperature = NULL;
lv_obj_t *ui_airTemperatureText = NULL;
lv_obj_t *ui_weatherInfo = NULL;
lv_obj_t *ui_weatherInfoText = NULL;
lv_obj_t *ui_weatherTemperature = NULL;
lv_obj_t *ui_weatherState = NULL;
lv_obj_t *ui_weatherImg = NULL;
lv_obj_t *ui_musicInfo = NULL;
lv_obj_t *ui_musicInfoText = NULL;
lv_obj_t *ui_singer = NULL;
lv_obj_t *ui_songName = NULL;
lv_obj_t *ui_playControl = NULL;
lv_obj_t *ui_play = NULL;
lv_obj_t *ui_last = NULL;
lv_obj_t *ui_next = NULL;
lv_obj_t *ui_footer = NULL;
lv_obj_t *ui_airControl = NULL;
lv_obj_t *ui_lower = NULL;
lv_obj_t *ui_increase = NULL;
lv_obj_t *ui_temperatureText = NULL;
lv_obj_t *ui_footerLeft = NULL;
lv_obj_t *ui_lightOn = NULL;
lv_obj_t *ui_lightOnImg = NULL;
lv_obj_t *ui_lightOnText = NULL;
lv_obj_t *ui_lightOff = NULL;
lv_obj_t *ui_lightOffImg = NULL;
lv_obj_t *ui_lightOffText = NULL;
lv_obj_t *ui_footerRight = NULL;
lv_obj_t *ui_curtainOn = NULL;
lv_obj_t *ui_curtainOnImg = NULL;
lv_obj_t *ui_curtainOnText = NULL;
lv_obj_t *ui_lightOff1 = NULL;
lv_obj_t *ui_curtainOffImg = NULL;
lv_obj_t *ui_curtainOffText = NULL;

// event funtions
void ui_event_airOnOffText(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        airOnOffText(e);
    }
}

// 增加屏幕跳转事件
void ui_event_ChangeRoom(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        roomChange(e);
    }
}

void ui_event_goHome(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange1(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_gobed(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange2(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_relex(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange3(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_getUp(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange4(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_cinema(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange5(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_goOut(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange6(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_lightSlider(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_slider_set_text_value(ui_lightSliderValue, target, "", "%");
    }
}

void ui_event_play(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        playSong(e);
    }
}

void ui_event_last(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        prevSong(e);
    }
}

void ui_event_next(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        nextSong(e);
    }
}

void ui_event_lower(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        decreaseTemp(e, ui_airTemperature, ui_temperatureText);
    }
}

void ui_event_increase(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        increaseTemp(e, ui_airTemperature, ui_temperatureText);
    }
}

void ui_event_temperatureText(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_checked_set_text_value(ui_airTemperature, target, "", "°C");
    }
}

// 灯全开灯全关事件
void ui_event_lightOnImg(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        lightAllOn(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_lightOffImg(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        lightAllOff(e, ui_lightOnImg, ui_lightOffImg, ui_lightSliderValue, ui_lightSlider);
    }
}

void ui_event_curtainOnImg(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        curtainAllOn(e, ui_curtainOnImg, ui_curtainOffImg);
    }
}

void ui_event_curtainOffImg(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        curtainAllOff(e, ui_curtainOnImg, ui_curtainOffImg);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    // 天气信息获取

    // 1.创建客户端通信对象
    int tcp_socket = socket(AF_INET, SOCK_STREAM, 0);

    // 2.设置 HTTP 服务器地址信息
    struct sockaddr_in addr;
    addr.sin_family = AF_INET;                         // IPV4 协议
    addr.sin_port = htons(80);                         // HTTP默认端口为  80
    addr.sin_addr.s_addr = inet_addr("120.77.134.57"); // 服务器IP

    // 2.连接服务器
    connect(tcp_socket, (struct sockaddr *)&addr, sizeof(addr));

    char Http_Request[512] = "GET /v3/weather/weatherInfo?key=6a1edf865110f3d7c628e88b2f31657d&city=440100 HTTP/1.1\r\nHost:restapi.amap.com\r\n\r\n";

    // 3.发送 HTTP 请求
    write(tcp_socket, Http_Request, strlen(Http_Request));

    // 4.读取服务器的应答数据
    char buffer[4096] = {0};

    read(tcp_socket, buffer, sizeof(buffer));

    char *tmp = strstr(buffer, "\r\n\r\n") + 4;

    cJSON *obj = cJSON_Parse(tmp);
    if (obj == NULL)
    {
        printf("parse json failed\n");
        close(tcp_socket);
        return;
    }

    // 获取lives数组
    cJSON *lives_array = cJSON_GetObjectItem(obj, "lives");
    if (lives_array == NULL || !cJSON_IsArray(lives_array))
    {
        printf("获取lives数组失败\n");
        cJSON_Delete(obj);
        close(tcp_socket);
        return;
    }

    // 获取数组大小
    int array_size = cJSON_GetArraySize(lives_array);
    cJSON *weather;
    cJSON *temperature;

    // 保存天气数据的字符串
    char weather_str[64] = "晴"; // 默认值
    char temp_str[32] = "23";    // 默认值

    // 循环遍历lives数组中的每个元素
    for (int i = 0; i < array_size; i++)
    {
        cJSON *live_item = cJSON_GetArrayItem(lives_array, i);
        if (live_item == NULL)
            continue;
        weather = cJSON_GetObjectItem(live_item, "weather");
        temperature = cJSON_GetObjectItem(live_item, "temperature");

        // 保存天气和温度数据
        if (weather && cJSON_GetStringValue(weather))
        {
            strncpy(weather_str, cJSON_GetStringValue(weather), sizeof(weather_str) - 1);
            weather_str[sizeof(weather_str) - 1] = '\0';
        }
        if (temperature && cJSON_GetStringValue(temperature))
        {
            strncpy(temp_str, cJSON_GetStringValue(temperature), sizeof(temp_str) - 1);
            temp_str[sizeof(temp_str) - 1] = '\0';
        }
    }

    // 释放JSON对象内存
    cJSON_Delete(obj);

    // 5.关闭连接
    close(tcp_socket);

    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_entirety = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_entirety, 800);
    lv_obj_set_height(ui_entirety, 480);
    lv_obj_set_align(ui_entirety, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_entirety, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_entirety, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_entirety, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_entirety, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header = lv_obj_create(ui_entirety);
    lv_obj_set_width(ui_header, 750);
    lv_obj_set_height(ui_header, 50);
    lv_obj_set_align(ui_header, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_header, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo = lv_obj_create(ui_header);
    lv_obj_set_width(ui_Logo, 100);
    lv_obj_set_height(ui_Logo, 50);
    lv_obj_set_align(ui_Logo, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Logo, lv_color_hex(0x0C0C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Logo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Logo, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImg = lv_image_create(ui_Logo);
    lv_image_set_src(ui_LogoImg, &ui_img_home_png);
    lv_obj_set_width(ui_LogoImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LogoImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LogoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LogoImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_roomCut = lv_obj_create(ui_header);
    lv_obj_set_width(ui_roomCut, 150);
    lv_obj_set_height(ui_roomCut, 50);
    lv_obj_set_x(ui_roomCut, 120);
    lv_obj_set_y(ui_roomCut, 0);
    lv_obj_set_align(ui_roomCut, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_roomCut, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_roomCut, lv_color_hex(0x101314), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roomCut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_roomCut, lv_color_hex(0x959595), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_roomCut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_roomCut, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomImg = lv_image_create(ui_roomCut);
    lv_image_set_src(ui_roomImg, &ui_img_sofa_png);
    lv_obj_set_width(ui_roomImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_roomImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_roomImg, -10);
    lv_obj_set_y(ui_roomImg, 0);
    lv_obj_set_align(ui_roomImg, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_roomImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_roomImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ChangeRoom = lv_dropdown_create(ui_roomCut);
    lv_dropdown_set_options(ui_ChangeRoom, "客厅\n主卧\n次卧");
    lv_dropdown_set_selected_highlight(ui_ChangeRoom, false);
    lv_dropdown_set_text(ui_ChangeRoom, "客厅");
    lv_obj_set_width(ui_ChangeRoom, 100);
    lv_obj_set_height(ui_ChangeRoom, 50);
    lv_obj_set_x(ui_ChangeRoom, 25);
    lv_obj_set_y(ui_ChangeRoom, 0);
    lv_obj_set_align(ui_ChangeRoom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChangeRoom, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_ChangeRoom, LV_OBJ_FLAG_PRESS_LOCK);   /// Flags
    lv_obj_set_style_text_color(ui_ChangeRoom, lv_color_hex(0x8E8E8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChangeRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChangeRoom, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChangeRoom, lv_color_hex(0x141316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeRoom, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_ChangeRoom, &lv_font_montserrat_16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ChangeRoom), lv_color_hex(0x7D7D7B),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ChangeRoom), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ChangeRoom), &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ChangeRoom), lv_color_hex(0x131416),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ChangeRoom), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_dropdown_get_list(ui_ChangeRoom), LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ChangeRoom), lv_color_hex(0x666666),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ChangeRoom), 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_currentTime = lv_obj_create(ui_header);
    lv_obj_set_width(ui_currentTime, 150);
    lv_obj_set_height(ui_currentTime, 50);
    lv_obj_set_align(ui_currentTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_currentTime, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_currentTime, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_currentTime, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_currentTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_currentTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_currentTime, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_currentTime);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Time, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Time, "14:20");
    lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_currentTime);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "2025年8月9日");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &ui_font_Date, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_obj_create(ui_header);
    lv_obj_set_width(ui_weather, 110);
    lv_obj_set_height(ui_weather, 50);
    lv_obj_set_x(ui_weather, -160);
    lv_obj_set_y(ui_weather, 0);
    lv_obj_set_align(ui_weather, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_weather, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherIcon = lv_image_create(ui_weather);
    if (strcmp(weather_str, "晴") == 0)
        lv_image_set_src(ui_weatherIcon, &ui_img_sun_png);
    else if (strcmp(weather_str, "小雨") == 0)
        lv_image_set_src(ui_weatherIcon, &light_rain);
    else if (strcmp(weather_str, "中雨") == 0)
        lv_image_set_src(ui_weatherIcon, &mid_rain);
    else if (strcmp(weather_str, "大雨") == 0)
        lv_image_set_src(ui_weatherIcon, &heavy_rain);
    else if (strcmp(weather_str, "多云") == 0)
        lv_image_set_src(ui_weatherIcon, &cloudy);
    else if (strcmp(weather_str, "阴") == 0)
        lv_image_set_src(ui_weatherIcon, &cloud);
    else
    lv_obj_set_width(ui_weatherIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherIcon, 2);
    lv_obj_set_y(ui_weatherIcon, 0);
    lv_obj_set_align(ui_weatherIcon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weatherIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperature = lv_label_create(ui_weather);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperature, LV_ALIGN_RIGHT_MID);
    char temp_display[32];
    snprintf(temp_display, sizeof(temp_display), "%s°C", temp_str);
    lv_label_set_text(ui_temperature, temp_display);
    lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_states = lv_obj_create(ui_header);
    lv_obj_set_width(ui_states, 140);
    lv_obj_set_height(ui_states, 50);
    lv_obj_set_align(ui_states, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_states, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_states, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_states, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_states, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi = lv_image_create(ui_states);
    lv_image_set_src(ui_wifi, &ui_img_wifi_png);
    lv_obj_set_width(ui_wifi, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifi, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifi, 2);
    lv_obj_set_y(ui_wifi, 0);
    lv_obj_set_align(ui_wifi, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_battery = lv_image_create(ui_states);
    lv_image_set_src(ui_battery, &ui_img_battery_png);
    lv_obj_set_width(ui_battery, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_battery, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_battery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_battery, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperature1 = lv_label_create(ui_states);
    lv_obj_set_width(ui_temperature1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperature1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperature1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_temperature1, "80%");
    lv_obj_set_style_text_color(ui_temperature1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main = lv_obj_create(ui_entirety);
    lv_obj_set_width(ui_main, 750);
    lv_obj_set_height(ui_main, 300);
    lv_obj_set_x(ui_main, 0);
    lv_obj_set_y(ui_main, -15);
    lv_obj_set_align(ui_main, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_main, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlState = lv_obj_create(ui_main);
    lv_obj_set_width(ui_controlState, 245);
    lv_obj_set_height(ui_controlState, 250);
    lv_obj_set_x(ui_controlState, 1);
    lv_obj_set_y(ui_controlState, 0);
    lv_obj_set_align(ui_controlState, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_controlState, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_controlState, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_controlState, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_controlState, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_controlState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_controlState, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goHome = lv_obj_create(ui_controlState);
    lv_obj_set_width(ui_goHome, 95);
    lv_obj_set_height(ui_goHome, 60);
    lv_obj_remove_flag(ui_goHome, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_goHome, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_goHome, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home = lv_image_create(ui_goHome);
    lv_image_set_src(ui_home, &ui_img_enter_png);
    lv_obj_set_width(ui_home, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_home, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_home, -10);
    lv_obj_set_y(ui_home, 0);
    lv_obj_set_align(ui_home, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_home, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goHomeText = lv_label_create(ui_goHome);
    lv_obj_set_width(ui_goHomeText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goHomeText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goHomeText, 10);
    lv_obj_set_y(ui_goHomeText, 0);
    lv_obj_set_align(ui_goHomeText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goHomeText, "离开");
    lv_obj_set_style_text_color(ui_goHomeText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goHomeText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goHomeText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gobed = lv_obj_create(ui_controlState);
    lv_obj_set_width(ui_gobed, 95);
    lv_obj_set_height(ui_gobed, 60);
    lv_obj_remove_flag(ui_gobed, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_gobed, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gobed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_gobed, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bed = lv_image_create(ui_gobed);
    lv_image_set_src(ui_bed, &ui_img_bed_png);
    lv_obj_set_width(ui_bed, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_bed, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_bed, -10);
    lv_obj_set_y(ui_bed, 0);
    lv_obj_set_align(ui_bed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_bed, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bed, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goBedText = lv_label_create(ui_gobed);
    lv_obj_set_width(ui_goBedText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goBedText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goBedText, 10);
    lv_obj_set_y(ui_goBedText, 0);
    lv_obj_set_align(ui_goBedText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goBedText, "睡觉");
    lv_obj_set_style_text_color(ui_goBedText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goBedText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goBedText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_relex = lv_obj_create(ui_controlState);
    lv_obj_set_width(ui_relex, 95);
    lv_obj_set_height(ui_relex, 60);
    lv_obj_remove_flag(ui_relex, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_relex, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_relex, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_relex, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yoga = lv_image_create(ui_relex);
    lv_image_set_src(ui_yoga, &ui_img_yoga_png);
    lv_obj_set_width(ui_yoga, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_yoga, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_yoga, -10);
    lv_obj_set_y(ui_yoga, 0);
    lv_obj_set_align(ui_yoga, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_yoga, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_yoga, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_relexText = lv_label_create(ui_relex);
    lv_obj_set_width(ui_relexText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_relexText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_relexText, 10);
    lv_obj_set_y(ui_relexText, 0);
    lv_obj_set_align(ui_relexText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_relexText, "放松");
    lv_obj_set_style_text_color(ui_relexText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_relexText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_relexText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getUp = lv_obj_create(ui_controlState);
    lv_obj_set_width(ui_getUp, 95);
    lv_obj_set_height(ui_getUp, 60);
    lv_obj_remove_flag(ui_getUp, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_getUp, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_getUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_getUp, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tea = lv_image_create(ui_getUp);
    lv_image_set_src(ui_tea, &ui_img_855347034);
    lv_obj_set_width(ui_tea, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tea, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tea, -10);
    lv_obj_set_y(ui_tea, 0);
    lv_obj_set_align(ui_tea, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_tea, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tea, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_getUpText = lv_label_create(ui_getUp);
    lv_obj_set_width(ui_getUpText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_getUpText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_getUpText, 10);
    lv_obj_set_y(ui_getUpText, 0);
    lv_obj_set_align(ui_getUpText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_getUpText, "起床");
    lv_obj_set_style_text_color(ui_getUpText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_getUpText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_getUpText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cinema = lv_obj_create(ui_controlState);
    lv_obj_set_width(ui_cinema, 95);
    lv_obj_set_height(ui_cinema, 60);
    lv_obj_remove_flag(ui_cinema, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_cinema, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cinema, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cinema, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tape = lv_image_create(ui_cinema);
    lv_image_set_src(ui_tape, &ui_img_cinema_png);
    lv_obj_set_width(ui_tape, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tape, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tape, -10);
    lv_obj_set_y(ui_tape, 0);
    lv_obj_set_align(ui_tape, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_tape, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tape, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_cinemaText = lv_label_create(ui_cinema);
    lv_obj_set_width(ui_cinemaText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_cinemaText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_cinemaText, 10);
    lv_obj_set_y(ui_cinemaText, 0);
    lv_obj_set_align(ui_cinemaText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_cinemaText, "观影");
    lv_obj_set_style_text_color(ui_cinemaText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cinemaText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cinemaText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goOut = lv_obj_create(ui_controlState);
    lv_obj_set_width(ui_goOut, 95);
    lv_obj_set_height(ui_goOut, 60);
    lv_obj_remove_flag(ui_goOut, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_goOut, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goOut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_goOut, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goOutImg = lv_image_create(ui_goOut);
    lv_image_set_src(ui_goOutImg, &ui_img_logout_png);
    lv_obj_set_width(ui_goOutImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goOutImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goOutImg, -10);
    lv_obj_set_y(ui_goOutImg, 0);
    lv_obj_set_align(ui_goOutImg, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_goOutImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_goOutImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goOutText = lv_label_create(ui_goOut);
    lv_obj_set_width(ui_goOutText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goOutText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goOutText, 10);
    lv_obj_set_y(ui_goOutText, 0);
    lv_obj_set_align(ui_goOutText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goOutText, "进入");
    lv_obj_set_style_text_color(ui_goOutText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goOutText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goOutText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlPanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_controlPanel, 480);
    lv_obj_set_height(ui_controlPanel, 290);
    lv_obj_set_x(ui_controlPanel, 30);
    lv_obj_set_y(ui_controlPanel, 0);
    lv_obj_set_align(ui_controlPanel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_controlPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_controlPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_controlPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_controlPanel, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_controlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_controlPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightInfo = lv_obj_create(ui_controlPanel);
    lv_obj_set_width(ui_lightInfo, 210);
    lv_obj_set_height(ui_lightInfo, 120);
    lv_obj_set_align(ui_lightInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_lightInfo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_lightInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightInfo, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_lightInfo, &ui_img_orange_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_lightInfo, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightInfo, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightInfoTitle = lv_label_create(ui_lightInfo);
    lv_obj_set_width(ui_lightInfoTitle, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightInfoTitle, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_lightInfoTitle, "照明");
    lv_obj_set_style_text_color(ui_lightInfoTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightInfoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightInfoTitle, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightSliderValue = lv_label_create(ui_lightInfo);
    lv_obj_set_width(ui_lightSliderValue, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightSliderValue, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightSliderValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lightSliderValue, "50%");
    lv_obj_set_style_text_color(ui_lightSliderValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightSliderValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightSlider = lv_slider_create(ui_lightInfo);
    lv_slider_set_value(ui_lightSlider, 50, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_lightSlider) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_lightSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_lightSlider, 150);
    lv_obj_set_height(ui_lightSlider, 10);
    lv_obj_set_align(ui_lightSlider, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_lightSlider, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lightSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lightSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if (lv_obj_get_style_pad_top(ui_lightSlider, LV_PART_MAIN) > 0)
        lv_obj_set_style_pad_right(ui_lightSlider,
                                   lv_obj_get_style_pad_right(ui_lightSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_airInfo = lv_obj_create(ui_controlPanel);
    lv_obj_set_width(ui_airInfo, 210);
    lv_obj_set_height(ui_airInfo, 120);
    lv_obj_set_x(ui_airInfo, -1);
    lv_obj_set_y(ui_airInfo, 0);
    lv_obj_set_align(ui_airInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airInfo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_airInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_airInfo, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_airInfo, &ui_img_blue_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_airInfo, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_airInfo, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airInfoTitle = lv_label_create(ui_airInfo);
    lv_obj_set_width(ui_airInfoTitle, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airInfoTitle, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_airInfoTitle, "空调");
    lv_obj_set_style_text_color(ui_airInfoTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airInfoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airInfoTitle, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_airInfo);
    lv_obj_set_width(ui_Panel2, 150);
    lv_obj_set_height(ui_Panel2, 70);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 5);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airTemperature = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_airTemperature, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airTemperature, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_airTemperature, 0);
    lv_obj_set_y(ui_airTemperature, -5);
    lv_obj_set_align(ui_airTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airTemperature, "20°C");
    lv_obj_set_style_text_color(ui_airTemperature, lv_color_hex(0xA1A2A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airTemperature, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airTemperatureText = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_airTemperatureText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airTemperatureText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_airTemperatureText, 0);
    lv_obj_set_y(ui_airTemperatureText, 20);
    lv_obj_set_align(ui_airTemperatureText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airTemperatureText, "温度");
    lv_obj_set_style_text_color(ui_airTemperatureText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airTemperatureText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airTemperatureText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherInfo = lv_obj_create(ui_controlPanel);
    lv_obj_set_width(ui_weatherInfo, 210);
    lv_obj_set_height(ui_weatherInfo, 120);
    lv_obj_set_align(ui_weatherInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherInfo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_weatherInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weatherInfo, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_weatherInfo, &ui_img_green_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_weatherInfo, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_weatherInfo, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherInfoText = lv_label_create(ui_weatherInfo);
    lv_obj_set_width(ui_weatherInfoText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherInfoText, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_weatherInfoText, "天气");
    lv_obj_set_style_text_color(ui_weatherInfoText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherInfoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherInfoText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherTemperature = lv_label_create(ui_weatherInfo);
    lv_obj_set_width(ui_weatherTemperature, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherTemperature, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_weatherTemperature, LV_ALIGN_BOTTOM_MID);
    // 创建温度显示字符串，添加°C单位
    lv_label_set_text(ui_weatherTemperature, temp_display);

    lv_obj_set_style_text_color(ui_weatherTemperature, lv_color_hex(0xA1A2A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherTemperature, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherState = lv_label_create(ui_weatherInfo);
    lv_obj_set_width(ui_weatherState, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherState, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherState, 15);
    lv_obj_set_y(ui_weatherState, 0);
    lv_obj_set_align(ui_weatherState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherState, weather_str);
    lv_obj_set_style_text_color(ui_weatherState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherState, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherImg = lv_image_create(ui_weatherInfo);
    if (strcmp(weather_str, "晴") == 0)
        lv_image_set_src(ui_weatherImg, &ui_img_sun_png);
    else if (strcmp(weather_str, "小雨") == 0)
        lv_image_set_src(ui_weatherImg, &light_rain);
    else if (strcmp(weather_str, "中雨") == 0)
        lv_image_set_src(ui_weatherImg, &mid_rain);
    else if (strcmp(weather_str, "大雨") == 0)
        lv_image_set_src(ui_weatherImg, &heavy_rain);
    else if (strcmp(weather_str, "多云") == 0)
        lv_image_set_src(ui_weatherImg, &cloudy);
    else if (strcmp(weather_str, "阴") == 0)
        lv_image_set_src(ui_weatherImg, &cloud);

    lv_obj_set_width(ui_weatherImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherImg, -15);
    lv_obj_set_y(ui_weatherImg, 0);
    lv_obj_set_align(ui_weatherImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weatherImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_musicInfo = lv_obj_create(ui_controlPanel);
    lv_obj_set_width(ui_musicInfo, 210);
    lv_obj_set_height(ui_musicInfo, 120);
    lv_obj_set_x(ui_musicInfo, -1);
    lv_obj_set_y(ui_musicInfo, -3);
    lv_obj_set_align(ui_musicInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_musicInfo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_musicInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_musicInfo, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_musicInfo, &The_Way_I_Still_Love_You, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_musicInfo, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_musicInfo, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musicInfoText = lv_label_create(ui_musicInfo);
    lv_obj_set_width(ui_musicInfoText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_musicInfoText, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_musicInfoText, "音乐");
    lv_obj_set_style_text_color(ui_musicInfoText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_musicInfoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_musicInfoText, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_singer = lv_label_create(ui_musicInfo);
    lv_obj_set_width(ui_singer, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_singer, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_singer, 0);
    lv_obj_set_y(ui_singer, -5);
    lv_obj_set_align(ui_singer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_singer, "Ed Sheeran");
    lv_obj_set_style_text_color(ui_singer, lv_color_hex(0x989899), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_singer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_singer, &ui_font_musicMode14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songName = lv_label_create(ui_musicInfo);
    lv_obj_set_width(ui_songName, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_songName, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_songName, 0);
    lv_obj_set_y(ui_songName, 10);
    lv_obj_set_align(ui_songName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_songName, "Perfect");
    lv_obj_set_style_text_color(ui_songName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_songName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_songName, &ui_font_musicMode16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playControl = lv_obj_create(ui_musicInfo);
    lv_obj_set_width(ui_playControl, 200);
    lv_obj_set_height(ui_playControl, 40);
    lv_obj_set_x(ui_playControl, 0);
    lv_obj_set_y(ui_playControl, 20);
    lv_obj_set_align(ui_playControl, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_playControl, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_playControl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playControl, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_play = lv_image_create(ui_playControl);
    lv_image_set_src(ui_play, &play);
    lv_obj_set_width(ui_play, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_play, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_play, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_last = lv_image_create(ui_playControl);
    lv_image_set_src(ui_last, &ui_img_214448395);
    lv_obj_set_width(ui_last, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_last, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_last, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_last, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_last, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_next = lv_image_create(ui_playControl);
    lv_image_set_src(ui_next, &ui_img_end_png);
    lv_obj_set_width(ui_next, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_next, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_next, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_next, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_footer = lv_obj_create(ui_entirety);
    lv_obj_set_width(ui_footer, 710);
    lv_obj_set_height(ui_footer, 80);
    lv_obj_set_align(ui_footer, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_footer, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footer, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footer, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airControl = lv_obj_create(ui_footer);
    lv_obj_set_width(ui_airControl, 250);
    lv_obj_set_height(ui_airControl, 40);
    lv_obj_set_align(ui_airControl, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airControl, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_airControl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_airControl, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lower = lv_image_create(ui_airControl);
    lv_image_set_src(ui_lower, &ui_img_back_png);
    lv_obj_set_width(ui_lower, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lower, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lower, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_lower, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lower, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_increase = lv_image_create(ui_airControl);
    lv_image_set_src(ui_increase, &ui_img_forward_png);
    lv_obj_set_width(ui_increase, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_increase, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_increase, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_increase, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_increase, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperatureText = lv_label_create(ui_airControl);
    lv_obj_set_width(ui_temperatureText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperatureText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperatureText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureText, "20°C");
    lv_obj_set_style_text_color(ui_temperatureText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperatureText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperatureText, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_temperatureText, LV_OBJ_FLAG_CLICKABLE); /// 使标签可点击

    ui_footerLeft = lv_obj_create(ui_footer);
    lv_obj_set_width(ui_footerLeft, 200);
    lv_obj_set_height(ui_footerLeft, 80);
    lv_obj_set_align(ui_footerLeft, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_footerLeft, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footerLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footerLeft, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOn = lv_obj_create(ui_footerLeft);
    lv_obj_set_width(ui_lightOn, 69);
    lv_obj_set_height(ui_lightOn, 80);
    lv_obj_set_x(ui_lightOn, 0);
    lv_obj_set_y(ui_lightOn, 5);
    lv_obj_set_align(ui_lightOn, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_lightOn, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOn, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOnImg = lv_image_create(ui_lightOn);
    lv_image_set_src(ui_lightOnImg, &ui_img_920086830);
    lv_obj_set_width(ui_lightOnImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOnImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lightOnImg, 0);
    lv_obj_set_y(ui_lightOnImg, -10);
    lv_obj_set_align(ui_lightOnImg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_lightOnImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lightOnImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_lightOnText = lv_label_create(ui_lightOn);
    lv_obj_set_width(ui_lightOnText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOnText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightOnText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lightOnText, "灯全开");
    lv_obj_set_style_text_color(ui_lightOnText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightOnText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightOnText, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOff = lv_obj_create(ui_footerLeft);
    lv_obj_set_width(ui_lightOff, 69);
    lv_obj_set_height(ui_lightOff, 80);
    lv_obj_set_x(ui_lightOff, 0);
    lv_obj_set_y(ui_lightOff, 5);
    lv_obj_set_align(ui_lightOff, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_lightOff, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOff, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOffImg = lv_image_create(ui_lightOff);
    lv_image_set_src(ui_lightOffImg, &ui_img_light_png);
    lv_obj_set_width(ui_lightOffImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOffImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lightOffImg, 0);
    lv_obj_set_y(ui_lightOffImg, -10);
    lv_obj_set_align(ui_lightOffImg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_lightOffImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lightOffImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_lightOffText = lv_label_create(ui_lightOff);
    lv_obj_set_width(ui_lightOffText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOffText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightOffText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lightOffText, "灯全关");
    lv_obj_set_style_text_color(ui_lightOffText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightOffText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightOffText, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_footerRight = lv_obj_create(ui_footer);
    lv_obj_set_width(ui_footerRight, 200);
    lv_obj_set_height(ui_footerRight, 80);
    lv_obj_set_align(ui_footerRight, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_footerRight, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footerRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footerRight, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOn = lv_obj_create(ui_footerRight);
    lv_obj_set_width(ui_curtainOn, 69);
    lv_obj_set_height(ui_curtainOn, 80);
    lv_obj_set_x(ui_curtainOn, 0);
    lv_obj_set_y(ui_curtainOn, 5);
    lv_obj_set_align(ui_curtainOn, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_curtainOn, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_curtainOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtainOn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_curtainOn, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOnImg = lv_image_create(ui_curtainOn);
    lv_image_set_src(ui_curtainOnImg, &ui_img_1611275694);
    lv_obj_set_width(ui_curtainOnImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOnImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_curtainOnImg, 0);
    lv_obj_set_y(ui_curtainOnImg, -10);
    lv_obj_set_align(ui_curtainOnImg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_curtainOnImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtainOnImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_curtainOnText = lv_label_create(ui_curtainOn);
    lv_obj_set_width(ui_curtainOnText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOnText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_curtainOnText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_curtainOnText, "窗帘全开");
    lv_obj_set_style_text_color(ui_curtainOnText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_curtainOnText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_curtainOnText, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOff1 = lv_obj_create(ui_footerRight);
    lv_obj_set_width(ui_lightOff1, 69);
    lv_obj_set_height(ui_lightOff1, 80);
    lv_obj_set_x(ui_lightOff1, 0);
    lv_obj_set_y(ui_lightOff1, 5);
    lv_obj_set_align(ui_lightOff1, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_lightOff1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOff1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOff1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOff1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOffImg = lv_image_create(ui_lightOff1);
    lv_image_set_src(ui_curtainOffImg, &ui_img_1850939063);
    lv_obj_set_width(ui_curtainOffImg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOffImg, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_curtainOffImg, 0);
    lv_obj_set_y(ui_curtainOffImg, -10);
    lv_obj_set_align(ui_curtainOffImg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_curtainOffImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtainOffImg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_curtainOffText = lv_label_create(ui_lightOff1);
    lv_obj_set_width(ui_curtainOffText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOffText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_curtainOffText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_curtainOffText, "窗帘全关");
    lv_obj_set_style_text_color(ui_curtainOffText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_curtainOffText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_curtainOffText, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_goHome, ui_event_goHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gobed, ui_event_gobed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_relex, ui_event_relex, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_getUp, ui_event_getUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cinema, ui_event_cinema, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goOut, ui_event_goOut, LV_EVENT_ALL, NULL);
    // 添加屏幕跳转的事件回调
    lv_obj_add_event_cb(ui_ChangeRoom, ui_event_ChangeRoom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightSlider, ui_event_lightSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_play, ui_event_play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_last, ui_event_last, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_next, ui_event_next, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lower, ui_event_lower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_increase, ui_event_increase, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_temperatureText, ui_event_temperatureText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightOnImg, ui_event_lightOnImg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightOffImg, ui_event_lightOffImg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_curtainOnImg, ui_event_curtainOnImg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_curtainOffImg, ui_event_curtainOffImg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_temperatureText, ui_event_airOnOffText, LV_EVENT_ALL, NULL);

    // 注册时间和日期标签到时间管理器
    ui_time_manager_register_labels(ui_Time, ui_Date);

    // 创建一个管道文件
    mkfifo("/home/gec/pipe", 0777);
}

void ui_Screen1_screen_destroy(void)
{
    // 从时间管理器中注销时间标签
    ui_time_manager_unregister_labels(ui_Time, ui_Date);

    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_entirety = NULL;
    ui_header = NULL;
    ui_Logo = NULL;
    ui_LogoImg = NULL;
    ui_roomCut = NULL;
    ui_roomImg = NULL;
    ui_ChangeRoom = NULL;
    ui_currentTime = NULL;
    ui_Time = NULL;
    ui_Date = NULL;
    ui_weather = NULL;
    ui_weatherIcon = NULL;
    ui_temperature = NULL;
    ui_states = NULL;
    ui_wifi = NULL;
    ui_battery = NULL;
    ui_temperature1 = NULL;
    ui_main = NULL;
    ui_controlState = NULL;
    ui_goHome = NULL;
    ui_home = NULL;
    ui_goHomeText = NULL;
    ui_gobed = NULL;
    ui_bed = NULL;
    ui_goBedText = NULL;
    ui_relex = NULL;
    ui_yoga = NULL;
    ui_relexText = NULL;
    ui_getUp = NULL;
    ui_tea = NULL;
    ui_getUpText = NULL;
    ui_cinema = NULL;
    ui_tape = NULL;
    ui_cinemaText = NULL;
    ui_goOut = NULL;
    ui_goOutImg = NULL;
    ui_goOutText = NULL;
    ui_controlPanel = NULL;
    ui_lightInfo = NULL;
    ui_lightInfoTitle = NULL;
    ui_lightSliderValue = NULL;
    ui_lightSlider = NULL;
    ui_airInfo = NULL;
    ui_airInfoTitle = NULL;
    ui_Panel2 = NULL;
    ui_airTemperature = NULL;
    ui_airTemperatureText = NULL;
    ui_weatherInfo = NULL;
    ui_weatherInfoText = NULL;
    ui_weatherTemperature = NULL;
    ui_weatherState = NULL;
    ui_weatherImg = NULL;
    ui_musicInfo = NULL;
    ui_musicInfoText = NULL;
    ui_singer = NULL;
    ui_songName = NULL;
    ui_playControl = NULL;
    ui_play = NULL;
    ui_last = NULL;
    ui_next = NULL;
    ui_footer = NULL;
    ui_airControl = NULL;
    ui_lower = NULL;
    ui_increase = NULL;
    ui_temperatureText = NULL;
    ui_footerLeft = NULL;
    ui_lightOn = NULL;
    ui_lightOnImg = NULL;
    ui_lightOnText = NULL;
    ui_lightOff = NULL;
    ui_lightOffImg = NULL;
    ui_lightOffText = NULL;
    ui_footerRight = NULL;
    ui_curtainOn = NULL;
    ui_curtainOnImg = NULL;
    ui_curtainOnText = NULL;
    ui_lightOff1 = NULL;
    ui_curtainOffImg = NULL;
    ui_curtainOffText = NULL;
}
