// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C"
{
#endif

    // SCREEN: ui_Screen1
    extern void ui_Screen1_screen_init(void);
    extern void ui_Screen1_screen_destroy(void);
    extern lv_obj_t *ui_Screen1;
    extern lv_obj_t *ui_entirety;
    extern lv_obj_t *ui_header;
    extern lv_obj_t *ui_Logo;
    extern lv_obj_t *ui_LogoImg;
    extern lv_obj_t *ui_roomCut;
    extern lv_obj_t *ui_roomImg;
    extern lv_obj_t *ui_ChangeRoom;
    // 声明全局变量
    extern void ui_event_ChangeRoom(lv_event_t *e);
    extern lv_obj_t *ui_currentTime;
    extern lv_obj_t *ui_Time;
    extern lv_obj_t *ui_Date;
    extern lv_obj_t *ui_weather;
    extern lv_obj_t *ui_weatherIcon;
    extern lv_obj_t *ui_temperature;
    extern lv_obj_t *ui_states;
    extern lv_obj_t *ui_wifi;
    extern lv_obj_t *ui_battery;
    extern lv_obj_t *ui_temperature1;
    extern lv_obj_t *ui_main;
    extern lv_obj_t *ui_controlState;
    extern void ui_event_goHome(lv_event_t *e);
    extern lv_obj_t *ui_goHome;
    extern lv_obj_t *ui_home;
    extern lv_obj_t *ui_goHomeText;
    extern void ui_event_gobed(lv_event_t *e);
    extern lv_obj_t *ui_gobed;
    extern lv_obj_t *ui_bed;
    extern lv_obj_t *ui_goBedText;
    extern void ui_event_relex(lv_event_t *e);
    extern lv_obj_t *ui_relex;
    extern lv_obj_t *ui_yoga;
    extern lv_obj_t *ui_relexText;
    extern void ui_event_getUp(lv_event_t *e);
    extern lv_obj_t *ui_getUp;
    extern lv_obj_t *ui_tea;
    extern lv_obj_t *ui_getUpText;
    extern void ui_event_cinema(lv_event_t *e);
    extern lv_obj_t *ui_cinema;
    extern lv_obj_t *ui_tape;
    extern lv_obj_t *ui_cinemaText;
    extern void ui_event_goOut(lv_event_t *e);
    extern lv_obj_t *ui_goOut;
    extern lv_obj_t *ui_goOutImg;
    extern lv_obj_t *ui_goOutText;
    extern lv_obj_t *ui_controlPanel;
    extern lv_obj_t *ui_lightInfo;
    extern lv_obj_t *ui_lightInfoTitle;
    extern lv_obj_t *ui_lightSliderValue;
    extern void ui_event_lightSlider(lv_event_t *e);
    extern lv_obj_t *ui_lightSlider;
    extern lv_obj_t *ui_airInfo;
    extern lv_obj_t *ui_airInfoTitle;
    extern lv_obj_t *ui_Panel2;
    extern lv_obj_t *ui_airTemperature;
    extern lv_obj_t *ui_airTemperatureText;
    extern lv_obj_t *ui_weatherInfo;
    extern lv_obj_t *ui_weatherInfoText;
    extern lv_obj_t *ui_weatherTemperature;
    extern lv_obj_t *ui_weatherState;
    extern lv_obj_t *ui_weatherImg;
    extern lv_obj_t *ui_musicInfo;
    extern lv_obj_t *ui_musicInfoText;
    extern lv_obj_t *ui_singer;
    extern lv_obj_t *ui_songName;
    extern lv_obj_t *ui_playControl;
    extern void ui_event_play(lv_event_t *e);
    extern lv_obj_t *ui_play;
    extern void ui_event_last(lv_event_t *e);
    extern lv_obj_t *ui_last;
    extern void ui_event_next(lv_event_t *e);
    extern lv_obj_t *ui_next;
    extern lv_obj_t *ui_footer;
    extern lv_obj_t *ui_airControl;
    extern void ui_event_lower(lv_event_t *e);
    extern lv_obj_t *ui_lower;
    extern void ui_event_increase(lv_event_t *e);
    extern lv_obj_t *ui_increase;
    extern void ui_event_temperatureText(lv_event_t *e);
    extern lv_obj_t *ui_temperatureText;
    extern lv_obj_t *ui_footerLeft;
    extern lv_obj_t *ui_lightOn;
    extern void ui_event_lightOnImg(lv_event_t *e);
    extern lv_obj_t *ui_lightOnImg;
    extern lv_obj_t *ui_lightOnText;
    extern lv_obj_t *ui_lightOff;
    extern void ui_event_lightOffImg(lv_event_t *e);
    extern lv_obj_t *ui_lightOffImg;
    extern lv_obj_t *ui_lightOffText;
    extern lv_obj_t *ui_footerRight;
    extern lv_obj_t *ui_curtainOn;
    extern void ui_event_curtainOnImg(lv_event_t *e);
    extern lv_obj_t *ui_curtainOnImg;
    extern lv_obj_t *ui_curtainOnText;
    extern lv_obj_t *ui_lightOff1;
    extern void ui_event_curtainOffImg(lv_event_t *e);
    extern lv_obj_t *ui_curtainOffImg;
    extern lv_obj_t *ui_curtainOffText;
    // CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
