// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C"
{
#endif

    // SCREEN: ui_Screen3
    extern void ui_Screen3_screen_init(void);
    extern void ui_Screen3_screen_destroy(void);
    extern lv_obj_t *ui_Screen3;
    extern lv_obj_t *ui_entirety2;
    extern lv_obj_t *ui_header2;
    extern lv_obj_t *ui_Logo2;
    extern lv_obj_t *ui_LogoImg2;
    extern lv_obj_t *ui_roomCut2;
    extern lv_obj_t *ui_roomImg2;
    extern lv_obj_t *ui_ChangeRoom2;

    extern void ui_event_airOnOffText2(lv_event_t *e);
    extern void ui_event_ChangeRoom2(lv_event_t *e);
    extern lv_obj_t *ui_currentTime2;
    extern lv_obj_t *ui_Time2;
    extern lv_obj_t *ui_Date2;
    extern lv_obj_t *ui_weather2;
    extern lv_obj_t *ui_weatherIcon2;
    extern lv_obj_t *ui_temperature4;
    extern lv_obj_t *ui_states2;
    extern lv_obj_t *ui_wifi2;
    extern lv_obj_t *ui_battery2;
    extern lv_obj_t *ui_temperature5;
    extern lv_obj_t *ui_main2;
    extern lv_obj_t *ui_controlState2;
    extern void ui_event_goHome2(lv_event_t *e);
    extern lv_obj_t *ui_goHome2;
    extern lv_obj_t *ui_home2;
    extern lv_obj_t *ui_goHomeText2;
    extern void ui_event_gobed2(lv_event_t *e);
    extern lv_obj_t *ui_gobed2;
    extern lv_obj_t *ui_bed2;
    extern lv_obj_t *ui_goBedText2;
    extern void ui_event_relex2(lv_event_t *e);
    extern lv_obj_t *ui_relex2;
    extern lv_obj_t *ui_yoga2;
    extern lv_obj_t *ui_relexText2;
    extern void ui_event_getUp2(lv_event_t *e);
    extern lv_obj_t *ui_getUp2;
    extern lv_obj_t *ui_tea2;
    extern lv_obj_t *ui_getUpText2;
    extern void ui_event_cinema2(lv_event_t *e);
    extern lv_obj_t *ui_cinema2;
    extern lv_obj_t *ui_tape2;
    extern lv_obj_t *ui_cinemaText2;
    extern void ui_event_goOut2(lv_event_t *e);
    extern lv_obj_t *ui_goOut2;
    extern lv_obj_t *ui_goOutImg2;
    extern lv_obj_t *ui_goOutText2;
    extern lv_obj_t *ui_controlPanel2;
    extern lv_obj_t *ui_lightInfo2;
    extern lv_obj_t *ui_lightInfoTitle2;
    extern lv_obj_t *ui_lightSliderValue2;
    extern void ui_event_lightSlider2(lv_event_t *e);
    extern lv_obj_t *ui_lightSlider2;
    extern lv_obj_t *ui_airInfo2;
    extern lv_obj_t *ui_airInfoTitle2;
    extern lv_obj_t *ui_Panel3;
    extern lv_obj_t *ui_airTemperature2;
    extern lv_obj_t *ui_airTemperatureText2;
    extern lv_obj_t *ui_weatherInfo2;
    extern lv_obj_t *ui_weatherInfoText2;
    extern lv_obj_t *ui_weatherTemperature2;
    extern lv_obj_t *ui_weatherState2;
    extern lv_obj_t *ui_weatherImg2;
    extern lv_obj_t *ui_musicInfo2;
    extern lv_obj_t *ui_musicInfoText2;
    extern lv_obj_t *ui_singer2;
    extern lv_obj_t *ui_songName2;
    extern lv_obj_t *ui_playControl2;
    extern void ui_event_play2(lv_event_t *e);
    extern lv_obj_t *ui_play2;
    extern void ui_event_last2(lv_event_t *e);
    extern lv_obj_t *ui_last2;
    extern void ui_event_next2(lv_event_t *e);
    extern lv_obj_t *ui_next2;
    extern lv_obj_t *ui_footer2;
    extern lv_obj_t *ui_airControl2;
    extern void ui_event_lower2(lv_event_t *e);
    extern lv_obj_t *ui_lower2;
    extern void ui_event_increase2(lv_event_t *e);
    extern lv_obj_t *ui_increase2;
    extern void ui_event_temperatureText2(lv_event_t *e);
    extern lv_obj_t *ui_temperatureText2;
    extern lv_obj_t *ui_footerLeft2;
    extern lv_obj_t *ui_lightOn2;
    extern void ui_event_lightOnImg2(lv_event_t *e);
    extern lv_obj_t *ui_lightOnImg2;
    extern lv_obj_t *ui_lightOnText2;
    extern lv_obj_t *ui_lightOff4;
    extern void ui_event_lightOffImg2(lv_event_t *e);
    extern lv_obj_t *ui_lightOffImg2;
    extern lv_obj_t *ui_lightOffText2;
    extern lv_obj_t *ui_footerRight2;
    extern lv_obj_t *ui_curtainOn2;
    extern void ui_event_curtainOnImg2(lv_event_t *e);
    extern lv_obj_t *ui_curtainOnImg2;
    extern lv_obj_t *ui_curtainOnText2;
    extern lv_obj_t *ui_lightOff5;
    extern void ui_event_curtainOffImg2(lv_event_t *e);
    extern lv_obj_t *ui_curtainOffImg2;
    extern lv_obj_t *ui_curtainOffText2;
    // CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
