// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_time_manager.h"
#include "ui_weather.h"

lv_obj_t *ui_Screen2 = NULL;
lv_obj_t *ui_entirety1 = NULL;
lv_obj_t *ui_header1 = NULL;
lv_obj_t *ui_Logo1 = NULL;
lv_obj_t *ui_LogoImg1 = NULL;
lv_obj_t *ui_roomCut1 = NULL;
lv_obj_t *ui_roomImg1 = NULL;
lv_obj_t *ui_ChangeRoom1 = NULL;
lv_obj_t *ui_currentTime1 = NULL;
lv_obj_t *ui_Time1 = NULL;
lv_obj_t *ui_Date1 = NULL;
lv_obj_t *ui_weather1 = NULL;
lv_obj_t *ui_weatherIcon1 = NULL;
lv_obj_t *ui_temperature2 = NULL;
lv_obj_t *ui_states1 = NULL;
lv_obj_t *ui_wifi1 = NULL;
lv_obj_t *ui_battery1 = NULL;
lv_obj_t *ui_temperature3 = NULL;
lv_obj_t *ui_main1 = NULL;
lv_obj_t *ui_controlState1 = NULL;
lv_obj_t *ui_goHome1 = NULL;
lv_obj_t *ui_home1 = NULL;
lv_obj_t *ui_goHomeText1 = NULL;
lv_obj_t *ui_gobed1 = NULL;
lv_obj_t *ui_bed1 = NULL;
lv_obj_t *ui_goBedText1 = NULL;
lv_obj_t *ui_relex1 = NULL;
lv_obj_t *ui_yoga1 = NULL;
lv_obj_t *ui_relexText1 = NULL;
lv_obj_t *ui_getUp1 = NULL;
lv_obj_t *ui_tea1 = NULL;
lv_obj_t *ui_getUpText1 = NULL;
lv_obj_t *ui_cinema1 = NULL;
lv_obj_t *ui_tape1 = NULL;
lv_obj_t *ui_cinemaText1 = NULL;
lv_obj_t *ui_goOut1 = NULL;
lv_obj_t *ui_goOutImg1 = NULL;
lv_obj_t *ui_goOutText1 = NULL;
lv_obj_t *ui_controlPanel1 = NULL;
lv_obj_t *ui_lightInfo1 = NULL;
lv_obj_t *ui_lightInfoTitle1 = NULL;
lv_obj_t *ui_lightSliderValue1 = NULL;
lv_obj_t *ui_lightSlider1 = NULL;
lv_obj_t *ui_airInfo1 = NULL;
lv_obj_t *ui_airInfoTitle1 = NULL;
lv_obj_t *ui_Panel1 = NULL;
lv_obj_t *ui_airTemperature1 = NULL;
lv_obj_t *ui_airTemperatureText1 = NULL;
lv_obj_t *ui_weatherInfo1 = NULL;
lv_obj_t *ui_weatherInfoText1 = NULL;
lv_obj_t *ui_weatherTemperature1 = NULL;
lv_obj_t *ui_weatherState1 = NULL;
lv_obj_t *ui_weatherImg1 = NULL;
lv_obj_t *ui_musicInfo1 = NULL;
lv_obj_t *ui_musicInfoText1 = NULL;
lv_obj_t *ui_singer1 = NULL;
lv_obj_t *ui_songName1 = NULL;
lv_obj_t *ui_playControl1 = NULL;
lv_obj_t *ui_play1 = NULL;
lv_obj_t *ui_last1 = NULL;
lv_obj_t *ui_next1 = NULL;
lv_obj_t *ui_footer1 = NULL;
lv_obj_t *ui_airControl1 = NULL;
lv_obj_t *ui_lower1 = NULL;
lv_obj_t *ui_increase1 = NULL;
lv_obj_t *ui_temperatureText1 = NULL;
lv_obj_t *ui_footerLeft1 = NULL;
lv_obj_t *ui_lightOn1 = NULL;
lv_obj_t *ui_lightOnImg1 = NULL;
lv_obj_t *ui_lightOnText1 = NULL;
lv_obj_t *ui_lightOff2 = NULL;
lv_obj_t *ui_lightOffImg1 = NULL;
lv_obj_t *ui_lightOffText1 = NULL;
lv_obj_t *ui_footerRight1 = NULL;
lv_obj_t *ui_curtainOn1 = NULL;
lv_obj_t *ui_curtainOnImg1 = NULL;
lv_obj_t *ui_curtainOnText1 = NULL;
lv_obj_t *ui_lightOff3 = NULL;
lv_obj_t *ui_curtainOffImg1 = NULL;
lv_obj_t *ui_curtainOffText1 = NULL;

// event funtions
void ui_event_airOnOffText1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        airOnOffText(e, ui_airTemperature1, ui_temperatureText1);
    }
}

void ui_event_ChangeRoom1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        roomChange(e);
    }
}

void ui_event_goHome1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange1(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1, "Room 1");
    }
}

void ui_event_gobed1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange2(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1, "Room 1");
    }
}

void ui_event_relex1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange3(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1, "Room 1");
    }
}

void ui_event_getUp1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange4(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1, "Room 1");
    }
}

void ui_event_cinema1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange5(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1, "Room 1");
    }
}

void ui_event_goOut1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        controlChange6(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1, "Room 1");
    }
}

// 防抖动变量 - Screen2
static uint32_t last_slider1_update_time = 0;
static int last_slider1_value = -1;

void ui_event_lightSlider1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        // 更新显示的百分比文本
        _ui_slider_set_text_value(ui_lightSliderValue1, target, "", "%");

        // 获取滑块当前值（0-100）
        int brightness = lv_slider_get_value(target);
        uint32_t current_time = lv_tick_get();

        // 防抖动：只有在值改变且距离上次发送超过100ms时才发送MQTT消息
        if (brightness != last_slider1_value && (current_time - last_slider1_update_time) > 100)
        {
            // 发送MQTT消息：主卧灯光亮度变化
            MQTT_send_light_brightness("Room 1", brightness);
            last_slider1_update_time = current_time;
            last_slider1_value = brightness;
        }
    }
}

void ui_event_play1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        playSong(e, ui_play1, ui_musicInfo1, ui_songName1, ui_singer1);
    }
}

void ui_event_last1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        prevSong(e, ui_last1, ui_musicInfo1, ui_songName1, ui_singer1);
    }
}

void ui_event_next1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        nextSong(e, ui_next1, ui_musicInfo1, ui_songName1, ui_singer1);
    }
}

void ui_event_lower1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        decreaseTemp(e, ui_airTemperature1, ui_temperatureText1);
    }
}

void ui_event_increase1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        increaseTemp(e, ui_airTemperature1, ui_temperatureText1);
    }
}

void ui_event_temperatureText1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_checked_set_text_value(ui_airTemperature1, target, "", "°C");
    }
}

void ui_event_airTemperature1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        airOnOffText(e, ui_airTemperature1, ui_temperatureText1);
    }
}

void ui_event_lightOnImg1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        lightAllOn(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1);
        // 发送MQTT消息：房间灯光开启
        MQTT_send_device_control("Room 1", "light", "on");
    }
}

void ui_event_lightOffImg1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        lightAllOff(e, ui_lightOnImg1, ui_lightOffImg1, ui_lightSliderValue1, ui_lightSlider1);

        // 发送MQTT消息：房间灯光关闭
        MQTT_send_device_control("Room 1", "light", "off");
    }
}

void ui_event_curtainOnImg1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        curtainAllOn(e, ui_curtainOnImg1, ui_curtainOffImg1);

        // 发送MQTT消息：房间窗帘打开
        MQTT_send_device_control("Room 1", "curtain", "on");
    }
}

void ui_event_curtainOffImg1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        curtainAllOff(e, ui_curtainOnImg1, ui_curtainOffImg1);

        // 发送MQTT消息：房间窗帘关闭
        MQTT_send_device_control("Room 1", "curtain", "off");
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    // 天气信息获取
    ui_weather_fetch();

    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen2, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_entirety1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_entirety1, 800);
    lv_obj_set_height(ui_entirety1, 480);
    lv_obj_set_align(ui_entirety1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_entirety1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_entirety1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_entirety1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_entirety1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header1 = lv_obj_create(ui_entirety1);
    lv_obj_set_width(ui_header1, 750);
    lv_obj_set_height(ui_header1, 50);
    lv_obj_set_align(ui_header1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_header1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_header1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo1 = lv_obj_create(ui_header1);
    lv_obj_set_width(ui_Logo1, 100);
    lv_obj_set_height(ui_Logo1, 50);
    lv_obj_set_align(ui_Logo1, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Logo1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Logo1, lv_color_hex(0x0C0C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Logo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Logo1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImg1 = lv_image_create(ui_Logo1);
    lv_image_set_src(ui_LogoImg1, &ui_img_home_png);
    lv_obj_set_width(ui_LogoImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LogoImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LogoImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LogoImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_roomCut1 = lv_obj_create(ui_header1);
    lv_obj_set_width(ui_roomCut1, 150);
    lv_obj_set_height(ui_roomCut1, 50);
    lv_obj_set_x(ui_roomCut1, 120);
    lv_obj_set_y(ui_roomCut1, 0);
    lv_obj_set_align(ui_roomCut1, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_roomCut1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_roomCut1, lv_color_hex(0x101314), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roomCut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_roomCut1, lv_color_hex(0x959595), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_roomCut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_roomCut1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomImg1 = lv_image_create(ui_roomCut1);
    lv_image_set_src(ui_roomImg1, &ui_img_sofa_png);
    lv_obj_set_width(ui_roomImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_roomImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_roomImg1, -10);
    lv_obj_set_y(ui_roomImg1, 0);
    lv_obj_set_align(ui_roomImg1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_roomImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_roomImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ChangeRoom1 = lv_dropdown_create(ui_roomCut1);
    lv_dropdown_set_options(ui_ChangeRoom1, "客厅\n主卧\n次卧");
    lv_dropdown_set_selected_highlight(ui_ChangeRoom1, false);
    lv_dropdown_set_text(ui_ChangeRoom1, "主卧");
    lv_obj_set_width(ui_ChangeRoom1, 100);
    lv_obj_set_height(ui_ChangeRoom1, 50);
    lv_obj_set_x(ui_ChangeRoom1, 25);
    lv_obj_set_y(ui_ChangeRoom1, 0);
    lv_obj_set_align(ui_ChangeRoom1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChangeRoom1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_text_color(ui_ChangeRoom1, lv_color_hex(0x8E8E8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChangeRoom1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChangeRoom1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChangeRoom1, lv_color_hex(0x141316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeRoom1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeRoom1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_ChangeRoom1, &lv_font_montserrat_16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ChangeRoom1), lv_color_hex(0x7D7D7B),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ChangeRoom1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ChangeRoom1), &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ChangeRoom1), lv_color_hex(0x131416),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ChangeRoom1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_dropdown_get_list(ui_ChangeRoom1), LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ChangeRoom1), lv_color_hex(0x666666),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ChangeRoom1), 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_currentTime1 = lv_obj_create(ui_header1);
    lv_obj_set_width(ui_currentTime1, 150);
    lv_obj_set_height(ui_currentTime1, 50);
    lv_obj_set_align(ui_currentTime1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_currentTime1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_currentTime1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_currentTime1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_currentTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_currentTime1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_currentTime1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time1 = lv_label_create(ui_currentTime1);
    lv_obj_set_width(ui_Time1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Time1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Time1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Time1, "14:20");
    lv_obj_set_style_text_color(ui_Time1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date1 = lv_label_create(ui_currentTime1);
    lv_obj_set_width(ui_Date1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Date1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Date1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date1, "2025年8月9日");
    lv_obj_set_style_text_color(ui_Date1, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date1, &ui_font_Date, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather1 = lv_obj_create(ui_header1);
    lv_obj_set_width(ui_weather1, 110);
    lv_obj_set_height(ui_weather1, 50);
    lv_obj_set_x(ui_weather1, -160);
    lv_obj_set_y(ui_weather1, 0);
    lv_obj_set_align(ui_weather1, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_weather1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_weather1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_weather1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherIcon1 = lv_image_create(ui_weather1);
    if (strcmp(weather_str, "晴") == 0)
        lv_image_set_src(ui_weatherIcon1, &ui_img_sun_png);
    else if (strcmp(weather_str, "小雨") == 0)
        lv_image_set_src(ui_weatherIcon1, &light_rain);
    else if (strcmp(weather_str, "中雨") == 0)
        lv_image_set_src(ui_weatherIcon1, &mid_rain);
    else if (strcmp(weather_str, "大雨") == 0)
        lv_image_set_src(ui_weatherIcon1, &heavy_rain);
    else if (strcmp(weather_str, "多云") == 0)
        lv_image_set_src(ui_weatherIcon1, &cloudy);
    else if (strcmp(weather_str, "阴") == 0)
        lv_image_set_src(ui_weatherIcon1, &cloud);
    else if (strcmp(weather_str, "雾") == 0)
        lv_image_set_src(ui_weatherIcon1, &fog);
    lv_obj_set_width(ui_weatherIcon1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherIcon1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherIcon1, 2);
    lv_obj_set_y(ui_weatherIcon1, 0);
    lv_obj_set_align(ui_weatherIcon1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weatherIcon1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weatherIcon1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperature2 = lv_label_create(ui_weather1);
    lv_obj_set_width(ui_temperature2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperature2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperature2, LV_ALIGN_RIGHT_MID);
    char temp_display[32];
    snprintf(temp_display, sizeof(temp_display), "%s°C", temp_str);
    lv_label_set_text(ui_temperature2, temp_display);
    lv_obj_set_style_text_color(ui_temperature2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_states1 = lv_obj_create(ui_header1);
    lv_obj_set_width(ui_states1, 140);
    lv_obj_set_height(ui_states1, 50);
    lv_obj_set_align(ui_states1, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_states1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_states1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_states1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_states1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi1 = lv_image_create(ui_states1);
    lv_image_set_src(ui_wifi1, &ui_img_wifi_png);
    lv_obj_set_width(ui_wifi1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifi1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifi1, 2);
    lv_obj_set_y(ui_wifi1, 0);
    lv_obj_set_align(ui_wifi1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_wifi1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_battery1 = lv_image_create(ui_states1);
    lv_image_set_src(ui_battery1, &ui_img_battery_png);
    lv_obj_set_width(ui_battery1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_battery1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_battery1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_battery1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperature3 = lv_label_create(ui_states1);
    lv_obj_set_width(ui_temperature3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperature3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperature3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_temperature3, "80%");
    lv_obj_set_style_text_color(ui_temperature3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main1 = lv_obj_create(ui_entirety1);
    lv_obj_set_width(ui_main1, 750);
    lv_obj_set_height(ui_main1, 300);
    lv_obj_set_x(ui_main1, 0);
    lv_obj_set_y(ui_main1, -15);
    lv_obj_set_align(ui_main1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_main1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_main1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_main1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlState1 = lv_obj_create(ui_main1);
    lv_obj_set_width(ui_controlState1, 245);
    lv_obj_set_height(ui_controlState1, 250);
    lv_obj_set_x(ui_controlState1, 1);
    lv_obj_set_y(ui_controlState1, 0);
    lv_obj_set_align(ui_controlState1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_controlState1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_controlState1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_controlState1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_controlState1, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_controlState1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_controlState1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goHome1 = lv_obj_create(ui_controlState1);
    lv_obj_set_width(ui_goHome1, 95);
    lv_obj_set_height(ui_goHome1, 60);
    lv_obj_remove_flag(ui_goHome1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_goHome1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goHome1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_goHome1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home1 = lv_image_create(ui_goHome1);
    lv_image_set_src(ui_home1, &ui_img_enter_png);
    lv_obj_set_width(ui_home1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_home1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_home1, -10);
    lv_obj_set_y(ui_home1, 0);
    lv_obj_set_align(ui_home1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_home1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_home1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goHomeText1 = lv_label_create(ui_goHome1);
    lv_obj_set_width(ui_goHomeText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goHomeText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goHomeText1, 10);
    lv_obj_set_y(ui_goHomeText1, 0);
    lv_obj_set_align(ui_goHomeText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goHomeText1, "离开");
    lv_obj_set_style_text_color(ui_goHomeText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goHomeText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goHomeText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gobed1 = lv_obj_create(ui_controlState1);
    lv_obj_set_width(ui_gobed1, 95);
    lv_obj_set_height(ui_gobed1, 60);
    lv_obj_remove_flag(ui_gobed1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_gobed1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gobed1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_gobed1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bed1 = lv_image_create(ui_gobed1);
    lv_image_set_src(ui_bed1, &ui_img_bed_png);
    lv_obj_set_width(ui_bed1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_bed1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_bed1, -10);
    lv_obj_set_y(ui_bed1, 0);
    lv_obj_set_align(ui_bed1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_bed1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bed1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goBedText1 = lv_label_create(ui_gobed1);
    lv_obj_set_width(ui_goBedText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goBedText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goBedText1, 10);
    lv_obj_set_y(ui_goBedText1, 0);
    lv_obj_set_align(ui_goBedText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goBedText1, "睡觉");
    lv_obj_set_style_text_color(ui_goBedText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goBedText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goBedText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_relex1 = lv_obj_create(ui_controlState1);
    lv_obj_set_width(ui_relex1, 95);
    lv_obj_set_height(ui_relex1, 60);
    lv_obj_remove_flag(ui_relex1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_relex1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_relex1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_relex1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yoga1 = lv_image_create(ui_relex1);
    lv_image_set_src(ui_yoga1, &ui_img_yoga_png);
    lv_obj_set_width(ui_yoga1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_yoga1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_yoga1, -10);
    lv_obj_set_y(ui_yoga1, 0);
    lv_obj_set_align(ui_yoga1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_yoga1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_yoga1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_relexText1 = lv_label_create(ui_relex1);
    lv_obj_set_width(ui_relexText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_relexText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_relexText1, 10);
    lv_obj_set_y(ui_relexText1, 0);
    lv_obj_set_align(ui_relexText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_relexText1, "放松");
    lv_obj_set_style_text_color(ui_relexText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_relexText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_relexText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getUp1 = lv_obj_create(ui_controlState1);
    lv_obj_set_width(ui_getUp1, 95);
    lv_obj_set_height(ui_getUp1, 60);
    lv_obj_remove_flag(ui_getUp1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_getUp1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_getUp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_getUp1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tea1 = lv_image_create(ui_getUp1);
    lv_image_set_src(ui_tea1, &ui_img_855347034);
    lv_obj_set_width(ui_tea1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tea1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tea1, -10);
    lv_obj_set_y(ui_tea1, 0);
    lv_obj_set_align(ui_tea1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_tea1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tea1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_getUpText1 = lv_label_create(ui_getUp1);
    lv_obj_set_width(ui_getUpText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_getUpText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_getUpText1, 10);
    lv_obj_set_y(ui_getUpText1, 0);
    lv_obj_set_align(ui_getUpText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_getUpText1, "起床");
    lv_obj_set_style_text_color(ui_getUpText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_getUpText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_getUpText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cinema1 = lv_obj_create(ui_controlState1);
    lv_obj_set_width(ui_cinema1, 95);
    lv_obj_set_height(ui_cinema1, 60);
    lv_obj_remove_flag(ui_cinema1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_cinema1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cinema1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cinema1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tape1 = lv_image_create(ui_cinema1);
    lv_image_set_src(ui_tape1, &ui_img_cinema_png);
    lv_obj_set_width(ui_tape1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tape1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tape1, -10);
    lv_obj_set_y(ui_tape1, 0);
    lv_obj_set_align(ui_tape1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_tape1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tape1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_cinemaText1 = lv_label_create(ui_cinema1);
    lv_obj_set_width(ui_cinemaText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_cinemaText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_cinemaText1, 10);
    lv_obj_set_y(ui_cinemaText1, 0);
    lv_obj_set_align(ui_cinemaText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_cinemaText1, "观影");
    lv_obj_set_style_text_color(ui_cinemaText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cinemaText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cinemaText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goOut1 = lv_obj_create(ui_controlState1);
    lv_obj_set_width(ui_goOut1, 95);
    lv_obj_set_height(ui_goOut1, 60);
    lv_obj_remove_flag(ui_goOut1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_goOut1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_goOut1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goOutImg1 = lv_image_create(ui_goOut1);
    lv_image_set_src(ui_goOutImg1, &ui_img_logout_png);
    lv_obj_set_width(ui_goOutImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goOutImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goOutImg1, -10);
    lv_obj_set_y(ui_goOutImg1, 0);
    lv_obj_set_align(ui_goOutImg1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_goOutImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_goOutImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_goOutText1 = lv_label_create(ui_goOut1);
    lv_obj_set_width(ui_goOutText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_goOutText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_goOutText1, 10);
    lv_obj_set_y(ui_goOutText1, 0);
    lv_obj_set_align(ui_goOutText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_goOutText1, "进入");
    lv_obj_set_style_text_color(ui_goOutText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goOutText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goOutText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlPanel1 = lv_obj_create(ui_main1);
    lv_obj_set_width(ui_controlPanel1, 480);
    lv_obj_set_height(ui_controlPanel1, 290);
    lv_obj_set_x(ui_controlPanel1, 30);
    lv_obj_set_y(ui_controlPanel1, 0);
    lv_obj_set_align(ui_controlPanel1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_controlPanel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_controlPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_controlPanel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_controlPanel1, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_controlPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_controlPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightInfo1 = lv_obj_create(ui_controlPanel1);
    lv_obj_set_width(ui_lightInfo1, 210);
    lv_obj_set_height(ui_lightInfo1, 120);
    lv_obj_set_align(ui_lightInfo1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_lightInfo1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_lightInfo1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightInfo1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightInfo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_lightInfo1, &ui_img_orange_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_lightInfo1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightInfo1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightInfoTitle1 = lv_label_create(ui_lightInfo1);
    lv_obj_set_width(ui_lightInfoTitle1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightInfoTitle1, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_lightInfoTitle1, "照明");
    lv_obj_set_style_text_color(ui_lightInfoTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightInfoTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightInfoTitle1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightSliderValue1 = lv_label_create(ui_lightInfo1);
    lv_obj_set_width(ui_lightSliderValue1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightSliderValue1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightSliderValue1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lightSliderValue1, "20%");
    lv_obj_set_style_text_color(ui_lightSliderValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightSliderValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightSlider1 = lv_slider_create(ui_lightInfo1);
    lv_slider_set_value(ui_lightSlider1, 20, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_lightSlider1) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_lightSlider1, 0,
                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_lightSlider1, 150);
    lv_obj_set_height(ui_lightSlider1, 10);
    lv_obj_set_align(ui_lightSlider1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_lightSlider1, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lightSlider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lightSlider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if (lv_obj_get_style_pad_top(ui_lightSlider1, LV_PART_MAIN) > 0)
        lv_obj_set_style_pad_right(ui_lightSlider1,
                                   lv_obj_get_style_pad_right(ui_lightSlider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_airInfo1 = lv_obj_create(ui_controlPanel1);
    lv_obj_set_width(ui_airInfo1, 210);
    lv_obj_set_height(ui_airInfo1, 120);
    lv_obj_set_x(ui_airInfo1, -1);
    lv_obj_set_y(ui_airInfo1, 0);
    lv_obj_set_align(ui_airInfo1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airInfo1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_airInfo1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_airInfo1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airInfo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_airInfo1, &ui_img_blue_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_airInfo1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_airInfo1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airInfoTitle1 = lv_label_create(ui_airInfo1);
    lv_obj_set_width(ui_airInfoTitle1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airInfoTitle1, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_airInfoTitle1, "空调");
    lv_obj_set_style_text_color(ui_airInfoTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airInfoTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airInfoTitle1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_airInfo1);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 70);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 5);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airTemperature1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_airTemperature1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airTemperature1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_airTemperature1, 0);
    lv_obj_set_y(ui_airTemperature1, -5);
    lv_obj_set_align(ui_airTemperature1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airTemperature1, "26°C");
    lv_obj_add_flag(ui_airTemperature1, LV_OBJ_FLAG_CLICKABLE); /// 让标签可点击
    lv_obj_set_style_text_color(ui_airTemperature1, lv_color_hex(0xA1A2A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airTemperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airTemperature1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airTemperatureText1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_airTemperatureText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_airTemperatureText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_airTemperatureText1, 0);
    lv_obj_set_y(ui_airTemperatureText1, 20);
    lv_obj_set_align(ui_airTemperatureText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_airTemperatureText1, "温度");
    lv_obj_set_style_text_color(ui_airTemperatureText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_airTemperatureText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airTemperatureText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherInfo1 = lv_obj_create(ui_controlPanel1);
    lv_obj_set_width(ui_weatherInfo1, 210);
    lv_obj_set_height(ui_weatherInfo1, 120);
    lv_obj_set_align(ui_weatherInfo1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherInfo1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_weatherInfo1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weatherInfo1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherInfo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_weatherInfo1, &ui_img_green_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_weatherInfo1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_weatherInfo1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherInfoText1 = lv_label_create(ui_weatherInfo1);
    lv_obj_set_width(ui_weatherInfoText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherInfoText1, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_weatherInfoText1, "天气");
    lv_obj_set_style_text_color(ui_weatherInfoText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherInfoText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherInfoText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherTemperature1 = lv_label_create(ui_weatherInfo1);
    lv_obj_set_width(ui_weatherTemperature1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherTemperature1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_weatherTemperature1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_weatherTemperature1, temp_display);
    lv_obj_set_style_text_color(ui_weatherTemperature1, lv_color_hex(0xA1A2A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherTemperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherTemperature1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherState1 = lv_label_create(ui_weatherInfo1);
    lv_obj_set_width(ui_weatherState1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherState1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherState1, 15);
    lv_obj_set_y(ui_weatherState1, 0);
    lv_obj_set_align(ui_weatherState1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherState1, weather_str);
    lv_obj_set_style_text_color(ui_weatherState1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherState1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherState1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherImg1 = lv_image_create(ui_weatherInfo1);
    if (strcmp(weather_str, "晴") == 0)
        lv_image_set_src(ui_weatherImg1, &ui_img_sun_png);
    else if (strcmp(weather_str, "小雨") == 0)
        lv_image_set_src(ui_weatherImg1, &light_rain);
    else if (strcmp(weather_str, "中雨") == 0)
        lv_image_set_src(ui_weatherImg1, &mid_rain);
    else if (strcmp(weather_str, "大雨") == 0)
        lv_image_set_src(ui_weatherImg1, &heavy_rain);
    else if (strcmp(weather_str, "多云") == 0)
        lv_image_set_src(ui_weatherImg1, &cloudy);
    else if (strcmp(weather_str, "阴") == 0)
        lv_image_set_src(ui_weatherImg1, &cloud);
    else if (strcmp(weather_str, "雾") == 0)
        lv_image_set_src(ui_weatherImg1, &fog);
    lv_obj_set_width(ui_weatherImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weatherImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weatherImg1, -15);
    lv_obj_set_y(ui_weatherImg1, 0);
    lv_obj_set_align(ui_weatherImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weatherImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_musicInfo1 = lv_obj_create(ui_controlPanel1);
    lv_obj_set_width(ui_musicInfo1, 210);
    lv_obj_set_height(ui_musicInfo1, 120);
    lv_obj_set_x(ui_musicInfo1, -1);
    lv_obj_set_y(ui_musicInfo1, -3);
    lv_obj_set_align(ui_musicInfo1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_musicInfo1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_musicInfo1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_musicInfo1, lv_color_hex(0x2E3033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicInfo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_musicInfo1, &The_Way_I_Still_Love_You, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_musicInfo1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_musicInfo1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musicInfoText1 = lv_label_create(ui_musicInfo1);
    lv_obj_set_width(ui_musicInfoText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_musicInfoText1, LV_SIZE_CONTENT); /// 1
    lv_label_set_text(ui_musicInfoText1, "音乐");
    lv_obj_set_style_text_color(ui_musicInfoText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_musicInfoText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_musicInfoText1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_singer1 = lv_label_create(ui_musicInfo1);
    lv_obj_set_width(ui_singer1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_singer1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_singer1, 0);
    lv_obj_set_y(ui_singer1, -5);
    lv_obj_set_align(ui_singer1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_singer1, "Ed Sheeran");
    lv_obj_set_style_text_color(ui_singer1, lv_color_hex(0x989899), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_singer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_singer1, &ui_font_musicMode14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songName1 = lv_label_create(ui_musicInfo1);
    lv_obj_set_width(ui_songName1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_songName1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_songName1, 0);
    lv_obj_set_y(ui_songName1, 10);
    lv_obj_set_align(ui_songName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_songName1, "Perfect");
    lv_obj_set_style_text_color(ui_songName1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_songName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_songName1, &ui_font_musicMode16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playControl1 = lv_obj_create(ui_musicInfo1);
    lv_obj_set_width(ui_playControl1, 200);
    lv_obj_set_height(ui_playControl1, 40);
    lv_obj_set_x(ui_playControl1, 0);
    lv_obj_set_y(ui_playControl1, 20);
    lv_obj_set_align(ui_playControl1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_playControl1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_playControl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playControl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playControl1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_play1 = lv_image_create(ui_playControl1);
    lv_image_set_src(ui_play1, &play);
    lv_obj_set_width(ui_play1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_play1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_play1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_play1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_last1 = lv_image_create(ui_playControl1);
    lv_image_set_src(ui_last1, &ui_img_214448395);
    lv_obj_set_width(ui_last1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_last1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_last1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_last1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_last1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_next1 = lv_image_create(ui_playControl1);
    lv_image_set_src(ui_next1, &ui_img_end_png);
    lv_obj_set_width(ui_next1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_next1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_next1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_next1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_footer1 = lv_obj_create(ui_entirety1);
    lv_obj_set_width(ui_footer1, 710);
    lv_obj_set_height(ui_footer1, 80);
    lv_obj_set_align(ui_footer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_footer1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footer1, lv_color_hex(0x1B1A1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footer1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airControl1 = lv_obj_create(ui_footer1);
    lv_obj_set_width(ui_airControl1, 250);
    lv_obj_set_height(ui_airControl1, 40);
    lv_obj_set_align(ui_airControl1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_airControl1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_airControl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_airControl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_airControl1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lower1 = lv_image_create(ui_airControl1);
    lv_image_set_src(ui_lower1, &ui_img_back_png);
    lv_obj_set_width(ui_lower1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lower1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lower1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_lower1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lower1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_increase1 = lv_image_create(ui_airControl1);
    lv_image_set_src(ui_increase1, &ui_img_forward_png);
    lv_obj_set_width(ui_increase1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_increase1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_increase1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_increase1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_increase1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperatureText1 = lv_label_create(ui_airControl1);
    lv_obj_set_width(ui_temperatureText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperatureText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_temperatureText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureText1, "26°C");
    lv_obj_set_style_text_color(ui_temperatureText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperatureText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperatureText1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_temperatureText1, LV_OBJ_FLAG_CLICKABLE); /// 使标签可点击

    ui_footerLeft1 = lv_obj_create(ui_footer1);
    lv_obj_set_width(ui_footerLeft1, 200);
    lv_obj_set_height(ui_footerLeft1, 80);
    lv_obj_set_align(ui_footerLeft1, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_footerLeft1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footerLeft1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerLeft1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footerLeft1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOn1 = lv_obj_create(ui_footerLeft1);
    lv_obj_set_width(ui_lightOn1, 69);
    lv_obj_set_height(ui_lightOn1, 80);
    lv_obj_set_x(ui_lightOn1, 0);
    lv_obj_set_y(ui_lightOn1, 5);
    lv_obj_set_align(ui_lightOn1, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_lightOn1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOn1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOnImg1 = lv_image_create(ui_lightOn1);
    lv_image_set_src(ui_lightOnImg1, &ui_img_920086830);
    lv_obj_set_width(ui_lightOnImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOnImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lightOnImg1, 0);
    lv_obj_set_y(ui_lightOnImg1, -10);
    lv_obj_set_align(ui_lightOnImg1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_lightOnImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lightOnImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_lightOnText1 = lv_label_create(ui_lightOn1);
    lv_obj_set_width(ui_lightOnText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOnText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightOnText1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lightOnText1, "灯全开");
    lv_obj_set_style_text_color(ui_lightOnText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightOnText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightOnText1, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOff2 = lv_obj_create(ui_footerLeft1);
    lv_obj_set_width(ui_lightOff2, 69);
    lv_obj_set_height(ui_lightOff2, 80);
    lv_obj_set_x(ui_lightOff2, 0);
    lv_obj_set_y(ui_lightOff2, 5);
    lv_obj_set_align(ui_lightOff2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_lightOff2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOff2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOff2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOff2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOffImg1 = lv_image_create(ui_lightOff2);
    lv_image_set_src(ui_lightOffImg1, &ui_img_light_png);
    lv_obj_set_width(ui_lightOffImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOffImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lightOffImg1, 0);
    lv_obj_set_y(ui_lightOffImg1, -10);
    lv_obj_set_align(ui_lightOffImg1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_lightOffImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lightOffImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_lightOffText1 = lv_label_create(ui_lightOff2);
    lv_obj_set_width(ui_lightOffText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lightOffText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lightOffText1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lightOffText1, "灯全关");
    lv_obj_set_style_text_color(ui_lightOffText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightOffText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightOffText1, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_footerRight1 = lv_obj_create(ui_footer1);
    lv_obj_set_width(ui_footerRight1, 200);
    lv_obj_set_height(ui_footerRight1, 80);
    lv_obj_set_align(ui_footerRight1, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_footerRight1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_footerRight1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerRight1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_footerRight1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOn1 = lv_obj_create(ui_footerRight1);
    lv_obj_set_width(ui_curtainOn1, 69);
    lv_obj_set_height(ui_curtainOn1, 80);
    lv_obj_set_x(ui_curtainOn1, 0);
    lv_obj_set_y(ui_curtainOn1, 5);
    lv_obj_set_align(ui_curtainOn1, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_curtainOn1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_curtainOn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtainOn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_curtainOn1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOnImg1 = lv_image_create(ui_curtainOn1);
    lv_image_set_src(ui_curtainOnImg1, &ui_img_1611275694);
    lv_obj_set_width(ui_curtainOnImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOnImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_curtainOnImg1, 0);
    lv_obj_set_y(ui_curtainOnImg1, -10);
    lv_obj_set_align(ui_curtainOnImg1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_curtainOnImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtainOnImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_curtainOnText1 = lv_label_create(ui_curtainOn1);
    lv_obj_set_width(ui_curtainOnText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOnText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_curtainOnText1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_curtainOnText1, "窗帘全开");
    lv_obj_set_style_text_color(ui_curtainOnText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_curtainOnText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_curtainOnText1, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightOff3 = lv_obj_create(ui_footerRight1);
    lv_obj_set_width(ui_lightOff3, 69);
    lv_obj_set_height(ui_lightOff3, 80);
    lv_obj_set_x(ui_lightOff3, 0);
    lv_obj_set_y(ui_lightOff3, 5);
    lv_obj_set_align(ui_lightOff3, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_lightOff3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_lightOff3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightOff3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lightOff3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtainOffImg1 = lv_image_create(ui_lightOff3);
    lv_image_set_src(ui_curtainOffImg1, &ui_img_1850939063);
    lv_obj_set_width(ui_curtainOffImg1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOffImg1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_curtainOffImg1, 0);
    lv_obj_set_y(ui_curtainOffImg1, -10);
    lv_obj_set_align(ui_curtainOffImg1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_curtainOffImg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtainOffImg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_curtainOffText1 = lv_label_create(ui_lightOff3);
    lv_obj_set_width(ui_curtainOffText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_curtainOffText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_curtainOffText1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_curtainOffText1, "窗帘全关");
    lv_obj_set_style_text_color(ui_curtainOffText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_curtainOffText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_curtainOffText1, &ui_font_font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_goHome1, ui_event_goHome1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_gobed1, ui_event_gobed1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_relex1, ui_event_relex1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_getUp1, ui_event_getUp1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_cinema1, ui_event_cinema1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_goOut1, ui_event_goOut1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ChangeRoom1, ui_event_ChangeRoom1, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_lightSlider1, ui_event_lightSlider1, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_play1, ui_event_play1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_last1, ui_event_last1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_next1, ui_event_next1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_lower1, ui_event_lower1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_increase1, ui_event_increase1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_airTemperature1, ui_event_airTemperature1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_temperatureText1, ui_event_temperatureText1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_lightOnImg1, ui_event_lightOnImg1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_lightOffImg1, ui_event_lightOffImg1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_curtainOnImg1, ui_event_curtainOnImg1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_curtainOffImg1, ui_event_curtainOffImg1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_temperatureText1, ui_event_airOnOffText1, LV_EVENT_CLICKED, NULL);

    // 注册时间和日期标签到时间管理器
    ui_time_manager_register_labels(ui_Time1, ui_Date1);

    // 创建一个管道文件
    mkfifo("/home/gec/pipe", 0777);
}

void ui_Screen2_screen_destroy(void)
{
    // 从时间管理器中注销时间标签
    ui_time_manager_unregister_labels(ui_Time1, ui_Date1);

    if (ui_Screen2)
        lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_entirety1 = NULL;
    ui_header1 = NULL;
    ui_Logo1 = NULL;
    ui_LogoImg1 = NULL;
    ui_roomCut1 = NULL;
    ui_roomImg1 = NULL;
    ui_ChangeRoom1 = NULL;
    ui_currentTime1 = NULL;
    ui_Time1 = NULL;
    ui_Date1 = NULL;
    ui_weather1 = NULL;
    ui_weatherIcon1 = NULL;
    ui_temperature2 = NULL;
    ui_states1 = NULL;
    ui_wifi1 = NULL;
    ui_battery1 = NULL;
    ui_temperature3 = NULL;
    ui_main1 = NULL;
    ui_controlState1 = NULL;
    ui_goHome1 = NULL;
    ui_home1 = NULL;
    ui_goHomeText1 = NULL;
    ui_gobed1 = NULL;
    ui_bed1 = NULL;
    ui_goBedText1 = NULL;
    ui_relex1 = NULL;
    ui_yoga1 = NULL;
    ui_relexText1 = NULL;
    ui_getUp1 = NULL;
    ui_tea1 = NULL;
    ui_getUpText1 = NULL;
    ui_cinema1 = NULL;
    ui_tape1 = NULL;
    ui_cinemaText1 = NULL;
    ui_goOut1 = NULL;
    ui_goOutImg1 = NULL;
    ui_goOutText1 = NULL;
    ui_controlPanel1 = NULL;
    ui_lightInfo1 = NULL;
    ui_lightInfoTitle1 = NULL;
    ui_lightSliderValue1 = NULL;
    ui_lightSlider1 = NULL;
    ui_airInfo1 = NULL;
    ui_airInfoTitle1 = NULL;
    ui_Panel1 = NULL;
    ui_airTemperature1 = NULL;
    ui_airTemperatureText1 = NULL;
    ui_weatherInfo1 = NULL;
    ui_weatherInfoText1 = NULL;
    ui_weatherTemperature1 = NULL;
    ui_weatherState1 = NULL;
    ui_weatherImg1 = NULL;
    ui_musicInfo1 = NULL;
    ui_musicInfoText1 = NULL;
    ui_singer1 = NULL;
    ui_songName1 = NULL;
    ui_playControl1 = NULL;
    ui_play1 = NULL;
    ui_last1 = NULL;
    ui_next1 = NULL;
    ui_footer1 = NULL;
    ui_airControl1 = NULL;
    ui_lower1 = NULL;
    ui_increase1 = NULL;
    ui_temperatureText1 = NULL;
    ui_footerLeft1 = NULL;
    ui_lightOn1 = NULL;
    ui_lightOnImg1 = NULL;
    ui_lightOnText1 = NULL;
    ui_lightOff2 = NULL;
    ui_lightOffImg1 = NULL;
    ui_lightOffText1 = NULL;
    ui_footerRight1 = NULL;
    ui_curtainOn1 = NULL;
    ui_curtainOnImg1 = NULL;
    ui_curtainOnText1 = NULL;
    ui_lightOff3 = NULL;
    ui_curtainOffImg1 = NULL;
    ui_curtainOffText1 = NULL;
}
