// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_light1 = NULL;
lv_obj_t * ui_curtain1 = NULL;
lv_obj_t * ui_airConditioner1 = NULL;
lv_obj_t * ui_loudSpeaker1 = NULL;
lv_obj_t * ui_airConditionerText1 = NULL;
lv_obj_t * ui_last1 = NULL;
lv_obj_t * ui_lastRoom1 = NULL;
lv_obj_t * ui_next1 = NULL;
lv_obj_t * ui_nextRoom1 = NULL;
lv_obj_t * ui_Room1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_lightValue1 = NULL;
// event funtions
void ui_event_light1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lightSwitch(e);
    }
}

void ui_event_curtain1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        curtainSwitch(e);
    }
}

void ui_event_loudSpeaker1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loudSpeakerSwitch(e);
    }
}

void ui_event_last1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_next1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lightValue1, target, "", "%");
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light1 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_light1, &ui_img_light_off_png);
    lv_obj_set_width(ui_light1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_light1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_light1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_light1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_curtain1 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_curtain1, &ui_img_curtain_off_png);
    lv_obj_set_width(ui_curtain1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_curtain1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_curtain1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_curtain1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtain1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airConditioner1 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_airConditioner1, &ui_img_air_conditioner_png);
    lv_obj_set_width(ui_airConditioner1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airConditioner1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_airConditioner1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_airConditioner1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_airConditioner1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loudSpeaker1 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_loudSpeaker1, &ui_img_loudspeaker_off_png);
    lv_obj_set_width(ui_loudSpeaker1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loudSpeaker1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loudSpeaker1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_loudSpeaker1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_loudSpeaker1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airConditionerText1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_airConditionerText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airConditionerText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_airConditionerText1, 0);
    lv_obj_set_y(ui_airConditionerText1, 100);
    lv_obj_set_align(ui_airConditionerText1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_airConditionerText1, "20°C");

    ui_last1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_last1, 100);
    lv_obj_set_height(ui_last1, 50);
    lv_obj_set_align(ui_last1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_last1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_last1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lastRoom1 = lv_label_create(ui_last1);
    lv_obj_set_width(ui_lastRoom1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastRoom1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lastRoom1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastRoom1, "last");
    lv_obj_set_style_text_font(ui_lastRoom1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_next1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_next1, 100);
    lv_obj_set_height(ui_next1, 50);
    lv_obj_set_align(ui_next1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_next1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_next1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nextRoom1 = lv_label_create(ui_next1);
    lv_obj_set_width(ui_nextRoom1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nextRoom1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_nextRoom1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nextRoom1, "next");
    lv_obj_set_style_text_font(ui_nextRoom1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Room1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Room1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Room1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Room1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Room1, "主卧");
    lv_obj_set_style_text_font(ui_Room1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen2);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -313);
    lv_obj_set_y(ui_Slider1, 72);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lightValue1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_lightValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightValue1, -312);
    lv_obj_set_y(ui_lightValue1, 96);
    lv_obj_set_align(ui_lightValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightValue1, "0%");

    lv_obj_add_event_cb(ui_light1, ui_event_light1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_curtain1, ui_event_curtain1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loudSpeaker1, ui_event_loudSpeaker1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_last1, ui_event_last1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_next1, ui_event_next1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_light1 = NULL;
    ui_curtain1 = NULL;
    ui_airConditioner1 = NULL;
    ui_loudSpeaker1 = NULL;
    ui_airConditionerText1 = NULL;
    ui_last1 = NULL;
    ui_lastRoom1 = NULL;
    ui_next1 = NULL;
    ui_nextRoom1 = NULL;
    ui_Room1 = NULL;
    ui_Slider1 = NULL;
    ui_lightValue1 = NULL;

}
