// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_light = NULL;
lv_obj_t * ui_curtain = NULL;
lv_obj_t * ui_airConditioner = NULL;
lv_obj_t * ui_loudSpeaker = NULL;
lv_obj_t * ui_airConditionerText = NULL;
lv_obj_t * ui_last = NULL;
lv_obj_t * ui_lastRoom = NULL;
lv_obj_t * ui_next = NULL;
lv_obj_t * ui_nextRoom = NULL;
lv_obj_t * ui_Room = NULL;
lv_obj_t * ui_Slider = NULL;
lv_obj_t * ui_lightValue = NULL;
// event funtions
void ui_event_light(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lightSwitch(e);
    }
}

void ui_event_curtain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        curtainSwitch(e);
    }
}

void ui_event_loudSpeaker(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loudSpeakerSwitch(e);
    }
}

void ui_event_last(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lightValue, target, "", "%");
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_light, &ui_img_light_off_png);
    lv_obj_set_width(ui_light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_light, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_light, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_curtain = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_curtain, &ui_img_curtain_off_png);
    lv_obj_set_width(ui_curtain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_curtain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_curtain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_curtain, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airConditioner = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_airConditioner, &ui_img_air_conditioner_png);
    lv_obj_set_width(ui_airConditioner, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airConditioner, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_airConditioner, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_airConditioner, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_airConditioner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loudSpeaker = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_loudSpeaker, &ui_img_loudspeaker_off_png);
    lv_obj_set_width(ui_loudSpeaker, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loudSpeaker, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loudSpeaker, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_loudSpeaker, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_loudSpeaker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airConditionerText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_airConditionerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airConditionerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_airConditionerText, 0);
    lv_obj_set_y(ui_airConditionerText, 100);
    lv_obj_set_align(ui_airConditionerText, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_airConditionerText, "20°C");

    ui_last = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_last, 100);
    lv_obj_set_height(ui_last, 50);
    lv_obj_set_align(ui_last, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_last, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_last, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lastRoom = lv_label_create(ui_last);
    lv_obj_set_width(ui_lastRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lastRoom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastRoom, "last");
    lv_obj_set_style_text_font(ui_lastRoom, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_next = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_next, 100);
    lv_obj_set_height(ui_next, 50);
    lv_obj_set_align(ui_next, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_next, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nextRoom = lv_label_create(ui_next);
    lv_obj_set_width(ui_nextRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nextRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_nextRoom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nextRoom, "next");
    lv_obj_set_style_text_font(ui_nextRoom, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Room = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Room, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Room, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Room, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Room, "客厅");
    lv_obj_set_style_text_font(ui_Room, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Slider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider, 150);
    lv_obj_set_height(ui_Slider, 10);
    lv_obj_set_x(ui_Slider, -313);
    lv_obj_set_y(ui_Slider, 72);
    lv_obj_set_align(ui_Slider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider,
                                                                                             lv_obj_get_style_pad_right(ui_Slider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lightValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lightValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightValue, -312);
    lv_obj_set_y(ui_lightValue, 96);
    lv_obj_set_align(ui_lightValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightValue, "50%");

    lv_obj_add_event_cb(ui_light, ui_event_light, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_curtain, ui_event_curtain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loudSpeaker, ui_event_loudSpeaker, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_last, ui_event_last, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_next, ui_event_next, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider, ui_event_Slider, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_light = NULL;
    ui_curtain = NULL;
    ui_airConditioner = NULL;
    ui_loudSpeaker = NULL;
    ui_airConditionerText = NULL;
    ui_last = NULL;
    ui_lastRoom = NULL;
    ui_next = NULL;
    ui_nextRoom = NULL;
    ui_Room = NULL;
    ui_Slider = NULL;
    ui_lightValue = NULL;

}
