// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern void ui_event_light2(lv_event_t * e);
extern lv_obj_t * ui_light2;
extern void ui_event_curtain2(lv_event_t * e);
extern lv_obj_t * ui_curtain2;
extern lv_obj_t * ui_airConditioner2;
extern void ui_event_loudSpeaker2(lv_event_t * e);
extern lv_obj_t * ui_loudSpeaker2;
extern lv_obj_t * ui_airConditionerText2;
extern void ui_event_last2(lv_event_t * e);
extern lv_obj_t * ui_last2;
extern lv_obj_t * ui_lastRoom2;
extern void ui_event_next2(lv_event_t * e);
extern lv_obj_t * ui_next2;
extern lv_obj_t * ui_nextRoom2;
extern lv_obj_t * ui_Room2;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_lightValue2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

