// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_light1(lv_event_t * e);
extern lv_obj_t * ui_light1;
extern void ui_event_curtain1(lv_event_t * e);
extern lv_obj_t * ui_curtain1;
extern lv_obj_t * ui_airConditioner1;
extern void ui_event_loudSpeaker1(lv_event_t * e);
extern lv_obj_t * ui_loudSpeaker1;
extern lv_obj_t * ui_airConditionerText1;
extern void ui_event_last1(lv_event_t * e);
extern lv_obj_t * ui_last1;
extern lv_obj_t * ui_lastRoom1;
extern void ui_event_next1(lv_event_t * e);
extern lv_obj_t * ui_next1;
extern lv_obj_t * ui_nextRoom1;
extern lv_obj_t * ui_Room1;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_lightValue1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

