// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_light(lv_event_t * e);
extern lv_obj_t * ui_light;
extern void ui_event_curtain(lv_event_t * e);
extern lv_obj_t * ui_curtain;
extern lv_obj_t * ui_airConditioner;
extern void ui_event_loudSpeaker(lv_event_t * e);
extern lv_obj_t * ui_loudSpeaker;
extern lv_obj_t * ui_airConditionerText;
extern void ui_event_last(lv_event_t * e);
extern lv_obj_t * ui_last;
extern lv_obj_t * ui_lastRoom;
extern void ui_event_next(lv_event_t * e);
extern lv_obj_t * ui_next;
extern lv_obj_t * ui_nextRoom;
extern lv_obj_t * ui_Room;
extern void ui_event_Slider(lv_event_t * e);
extern lv_obj_t * ui_Slider;
extern lv_obj_t * ui_lightValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

