// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_light2 = NULL;
lv_obj_t * ui_curtain2 = NULL;
lv_obj_t * ui_airConditioner2 = NULL;
lv_obj_t * ui_loudSpeaker2 = NULL;
lv_obj_t * ui_airConditionerText2 = NULL;
lv_obj_t * ui_last2 = NULL;
lv_obj_t * ui_lastRoom2 = NULL;
lv_obj_t * ui_next2 = NULL;
lv_obj_t * ui_nextRoom2 = NULL;
lv_obj_t * ui_Room2 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_lightValue2 = NULL;
// event funtions
void ui_event_light2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lightSwitch(e);
    }
}

void ui_event_curtain2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        curtainSwitch(e);
    }
}

void ui_event_loudSpeaker2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loudSpeakerSwitch(e);
    }
}

void ui_event_last2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_next2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lightValue2, target, "", "%");
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light2 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_light2, &ui_img_light_off_png);
    lv_obj_set_width(ui_light2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_light2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_light2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_light2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_curtain2 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_curtain2, &ui_img_curtain_off_png);
    lv_obj_set_width(ui_curtain2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_curtain2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_curtain2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_curtain2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_curtain2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airConditioner2 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_airConditioner2, &ui_img_air_conditioner_png);
    lv_obj_set_width(ui_airConditioner2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airConditioner2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_airConditioner2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_airConditioner2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_airConditioner2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loudSpeaker2 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_loudSpeaker2, &ui_img_loudspeaker_off_png);
    lv_obj_set_width(ui_loudSpeaker2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loudSpeaker2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loudSpeaker2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_loudSpeaker2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_loudSpeaker2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airConditionerText2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_airConditionerText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airConditionerText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_airConditionerText2, 0);
    lv_obj_set_y(ui_airConditionerText2, 100);
    lv_obj_set_align(ui_airConditionerText2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_airConditionerText2, "20°C");

    ui_last2 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_last2, 100);
    lv_obj_set_height(ui_last2, 50);
    lv_obj_set_align(ui_last2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_last2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_last2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lastRoom2 = lv_label_create(ui_last2);
    lv_obj_set_width(ui_lastRoom2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastRoom2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lastRoom2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastRoom2, "last");
    lv_obj_set_style_text_font(ui_lastRoom2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_next2 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_next2, 100);
    lv_obj_set_height(ui_next2, 50);
    lv_obj_set_align(ui_next2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_next2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_next2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nextRoom2 = lv_label_create(ui_next2);
    lv_obj_set_width(ui_nextRoom2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nextRoom2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_nextRoom2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nextRoom2, "next");
    lv_obj_set_style_text_font(ui_nextRoom2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Room2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Room2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Room2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Room2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Room2, "次卧");
    lv_obj_set_style_text_font(ui_Room2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Screen3);
    lv_slider_set_value(ui_Slider2, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, -313);
    lv_obj_set_y(ui_Slider2, 72);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lightValue2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_lightValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightValue2, -312);
    lv_obj_set_y(ui_lightValue2, 96);
    lv_obj_set_align(ui_lightValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightValue2, "50%");

    lv_obj_add_event_cb(ui_light2, ui_event_light2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_curtain2, ui_event_curtain2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loudSpeaker2, ui_event_loudSpeaker2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_last2, ui_event_last2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_next2, ui_event_next2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_light2 = NULL;
    ui_curtain2 = NULL;
    ui_airConditioner2 = NULL;
    ui_loudSpeaker2 = NULL;
    ui_airConditionerText2 = NULL;
    ui_last2 = NULL;
    ui_lastRoom2 = NULL;
    ui_next2 = NULL;
    ui_nextRoom2 = NULL;
    ui_Room2 = NULL;
    ui_Slider2 = NULL;
    ui_lightValue2 = NULL;

}
